### ISSUE TITLE
Wishlist: A way to figure out the right syntax for a ScriptEngineFactory

### ISSUE THREAD

**Issue by hakanai** [bobbylight/RSyntaxTextArea#103]
ScriptEngineFactory gives us multiple ways to identify a scripting language.
- getEngineName()
- getLanguageName()
- getMimeTypes()
- getNames()
- getExtensions()

Constant strings in RSyntax for MIME types seem to be a perfect fit. But I find that script engines have unexpected things. AppleScript declares "text/plain" as one of its MIME types, making it look like it isn't supported for syntax highlighting. (At the moment it isn't, but that's not the point.) JRuby declares application/x-ruby, but SyntaxConstants declares text/ruby.

I don't know how to match these two up, but there are a few disparate ideas:
- Provide a method to get a syntax for a language name or file extension and hope that ScriptEngineFactory implementations can be trusted to get those right.
- Provide a mapping for multiple MIME types to a single syntax MIME type. Then Ruby would be able to match up at least.

**Comment by bobbylight** [comment]
Closing as this is doable today [via FileTypeUtil](https://github.com/bobbylight/RSyntaxTextArea/blob/68ab6e86539ce0c4d3d2216713e063c2456a6090/RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/FileTypeUtil.java#L24-L49). I might add a utility method to convert from mime type strings to string constants supported by RSTA (along with a utility method on `RSyntaxTextArea` itself would be nice), but only if there is an expressed need for it. Please open a new ticket for that if you (or anyone else - I know this ticket is very very old) would like that!
