### ISSUE TITLE
K&R styled if statements don't fold correctly

### ISSUE THREAD

**Issue by illumi** [bobbylight/RSyntaxTextArea#116]
When folding the following:

    if (a < b) {
        // do something
    } else {
        // do something else
    }

The folded result is:

    if (a < b) {
        // do something else
    }

I would expect the correct folding to be the same as Notepad++:
    if (a < b) {

Note, for the case where there is a newline you should be able to fold the if and else blocks separately.

**Comment by bobbylight** [comment]
I believe this is now fixed.  Please verify if you get a chance.

**Comment by illumi** [comment]
Working as expected, thanks!
