### ISSUE TITLE
FindReplace example does not compile

### ISSUE THREAD

**Issue by johann-petrak** [bobbylight/RSyntaxTextArea#117]
The example in the wiki https://github.com/bobbylight/RSyntaxTextArea/wiki/Example:%20Using%20Find%20and%20Replace does not compile: 

FindAndReplaceDemo.java:83: error: incompatible types: SearchResult cannot be converted to boolean
      boolean found = SearchEngine.find(textArea, context);

This should maybe get replaced with 
  boolean found = (SearchEngine.find(textArea, context).getMatchRange() != null); 
ir similar?

**Comment by bobbylight** [comment]
Thanks, this is now fixed.
