### ISSUE TITLE
Feature Request: Enable displaying line numbers all the way down

### ISSUE THREAD

**Issue by joelmoniz** [bobbylight/RSyntaxTextArea#123]
Would it be possible to add in a method, (like `setAllLineNumbersVisible(boolean)`) to allow the user to choose whether or not all the line numbers are visible, even if so many lines have not yet been typed? For example,

`setAllLineNumbersVisible(false)` would make the line numbers display as:
![setAllLineNumbersVisible(false)](http://i210.photobucket.com/albums/bb180/pics_freakazoida/normal.png)

while
`setAllLineNumbersVisible(true)` would get them to display as:
![setAllLineNumbersVisible(true)](http://i210.photobucket.com/albums/bb180/pics_freakazoida/extended_lines.png)

**Comment by bobbylight** [comment]
I'm not interested in implementing this, and I do not believe it to be common in text editors to do so.

**Comment by joelmoniz** [comment]
Ah, I understand. I had brought up this issue, along with #124 and [this question](http://fifesoft.com/forum/viewtopic.php?f=10&t=963) I had asked on the forum because I am working on replacing [processing](https://processing.org/)'s JEditTextArea with the RSyyntaxTextArea, and am trying to mimic the editor's look and feel as closely as possible:

![image](https://cloud.githubusercontent.com/assets/4526417/8764828/19cd95ea-2e01-11e5-8df5-212a69553062.png)

Would it be alright if I sent in a PR sometime that takes a crack at implementing this feature (turned off by default, but which the user can enable), or is it not likely to be merged? Thanks!

**Comment by bobbylight** [comment]
Sure, pull requests are welcome.  Be sure to consider code folding and line wrap when working on this addition, since they affect the line numbering view.
