### ISSUE TITLE
Regression: Binary incompatible change in RTextScrollPane constructor

### ISSUE THREAD

**Issue by ncwoehler** [bobbylight/RSyntaxTextArea#126]
#28 has introduced a binary incompatible change of the RTextScrollPane constructor.
This [commit](https://github.com/bobbylight/RSyntaxTextArea/commit/48c65fb867f09425b780a09749588ecb4b4201f4) changed the constructor argument from RSyntaxTextArea to Component. Code compiling against the old version will not run with version 2.5.7 but will throw this error:
```
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: org.fife.ui.rtextarea.RTextScrollPane.<init>(Lorg/fife/ui/rtextarea/RTextArea;)V
```
To fix the binary incompatibility problem the old constructors have to be added again.

**Comment by bobbylight** [comment]
Fixed by merging #127.
