### ISSUE TITLE
Unable to set the background color of the ErrorStrip

### ISSUE THREAD

**Issue by joelmoniz** [bobbylight/RSyntaxTextArea#128]
The following code does not change the background color of the error strip:

```
ErrorStrip es = new ErrorStrip(textArea);
es.setBackground(Color.blue);
es.setOpaque(true);
```

The output produced is as shown:

![error_strip_bckgrnd](https://cloud.githubusercontent.com/assets/4526417/8726210/e20b8770-2be9-11e5-92bd-2e1ab041541e.PNG)

**Comment by bobbylight** [comment]
Thanks for this; fixed.  Note that `setOpaque(true)` is no longer necessary as the ErrorStrip is now opaque by default.

**Comment by joelmoniz** [comment]
Works like a charm. Thank you :)
