### ISSUE TITLE
JSON - Different format for Keys and Values

### ISSUE THREAD

**Issue by iNdieboyjeff** [bobbylight/RSyntaxTextArea#132]
is it possible to format JSON code so that keys (which are strings) are formatted (e.g. colour) differently to string values (which are also strings)

**Comment by bobbylight** [comment]
Not at present, and this would be a new feature.  I consider this low priority, so I probably will not be working on it for the foreseeable future.

Pull requests are welcome.  I suppose this would require a new `TokenType`(s).  Right now, RSTA's `TokenType`s are generic and not language-specific, so we'd have to come up with either a new generic-ish token type for "key", or one for "key" and another for "value".

**Comment by iNdieboyjeff** [comment]
Would it be possible to mark a key as a VARIABLE token, and then keep the value as-is?

If you can give me a pointer where I should be looking to do this I can see if I can modify the code myself.

**Comment by iNdieboyjeff** [comment]
Have submitted a pull request that adds this functionality
