### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by liscju** [bobbylight/RSyntaxTextArea#134]
I would like to use RSyntaxTextArea in checkstyle (https://github.com/checkstyle/checkstyle), and i have hesitation regarding including it in generated jar of the project. From what i have seen , when i declare dependency on RSyntaxTextArea in my maven file , when i build jar using "mvn clean package -Passembly"  it is not including license of RSyntaxTextArea in generated jar. What should i do to not violate your license restriction?

**Comment by bobbylight** [comment]
I'd be OK if you just dropped a file [containing the license](https://github.com/bobbylight/RSyntaxTextArea/blob/master/src/main/dist/RSyntaxTextArea.License.txt) in your lib folder, or wherever else you have license files or similar loose files.

Not being a Maven guy, perhaps I could tweak stuff to have the license dropped down when you generate the assembly.  Or are you saying it should be in the built jar itself?  I'm using Gradle for builds, but I'm not even a Gradle guy, so if you have strong opinions or advice it is welcome.  :)

**Comment by bobbylight** [comment]
I'm closing, but feel free to reopen with specifics on how a license is typically delivered.
