### ISSUE TITLE
Multiple highlights on the same line behave weirdly

### ISSUE THREAD

**Issue by matthijskooijman** [bobbylight/RSyntaxTextArea#161]
I've found that when two highlights are added onto the same line, removing one of them can result in the other one being removed instead. Digging into the source, I've found that the `LineHighlightInfo` class that is used to keep track of highlights [has an equals method](https://github.com/bobbylight/RSyntaxTextArea/blob/master/src/main/java/org/fife/ui/rtextarea/LineHighlightManager.java#L181-L190) that considers highlights equal if the offset matches, even if they are not identical objects.

I do not see any reason for this behaviour, so simply removing the equals method would be an easy fix. This does mean that the `compareTo()` method is now inconsistent with the `equals()` method (which, according to the Comparable documentation means it has "[a natural ordering that is inconsistent with equals](https://docs.oracle.com/javase/7/docs/api/java/lang/Comparable.html#compareTo%28T%29), which is not forbidden, but not recommended.

An easy way to fix that is to move the compareTo method into a separate Comparator class, and use that when inserting new highlights instead of relying on the natural ordering.

**Comment by bobbylight** [comment]
Good catch, I was probably only thinking of one-highlight-per-line scenarios (e.g. breakpoints on a line).

**Comment by matthijskooijman** [comment]
Looks good, thanks!
