### ISSUE TITLE
Forum registration broken

### ISSUE THREAD

**Issue by ryanhamilton** [bobbylight/RSyntaxTextArea#162]
Hi,
I tried to find a way to contact you direct but had no luck, so the only way I could think of was here.

http://fifesoft.com/forum/ucp.php?mode=register
Registration is broken. Broken php includes at the top and no "Confirmation code:" displayed.

Thanks for a piece of great software.
-Ryan

**Comment by bobbylight** [comment]
Should be fixed now, thanks!
