### ISSUE TITLE
Roundrobinautocompletion showing a info label for each completion provider

### ISSUE THREAD

**Issue by eitzenbe** [bobbylight/RSyntaxTextArea#166]
For the round robin AC it would be cool to have the option of displaying a label for each provider currently shown:
something like adding a set/get name method to the CompletionProvider interface, that is then used by the AutoCompletion to add a JLabel with that name to the contentpane of the AutoCompletePopupWindow , as it is a BorderLayout -> contentPane.add(JLabel, NORTH)

**Comment by bobbylight** [comment]
I'm marking this as a duplicate now that I've moved it to [AutoComplete #41](https://github.com/bobbylight/AutoComplete/issues/41).
