### ISSUE TITLE
Theme class to restrictive

### ISSUE THREAD

**Issue by eitzenbe** [bobbylight/RSyntaxTextArea#167]
Hi, 
I am  trying to access theme data (colors, fonts, ...) to make other frmaes/dialogs appear in the same color style. For that of course I would need access methods to the internal fields or at least a protected state so that I can derive from your theme class and add accessors on top... any chance?

btw: Fabulous piece of software you did

**Comment by bobbylight** [comment]
Ask and ye shall receive!  I made all fields protected, instead of adding getters and setters, as I don't envision it being typical for folks to do this.
