### ISSUE TITLE
How to get this work?

### ISSUE THREAD

**Issue by MaToxZ** [bobbylight/RSyntaxTextArea#168]
Hi, I'm a studying of Eng. Informatic, right now I'm developing a Collegue project wich is a kind of compiler of my own declared programming lenguage, and I want to import this Library to my project, to get those Code Editors features, but I'm going to be sincere, I didn't get this working yet, I downloaded from the official sourceforge website, the File i downloades a zip file, but It isn't seems to be a Java library, I read something about compiling with gradle, but I don't really know how to do this, I've been searching for kind of tutorial installation, but I don't got nothing about, that's why I come to you to ask you if anyone of you could help me with this? Thank you so much beforehand.

**Comment by bobbylight** [comment]
Hi @MaToxZ,

The binary zip file from SourceForge, `rsyntaxtextarea-2.5.7.zip`, should be unzipped with your favorite zip utility, e.g. WinZip or 7-zip on Windows.  Inside you'll find the RSTA jar.  You can write a demo application similer to the one on RSTA's wiki here:

https://github.com/bobbylight/RSyntaxTextArea/wiki/Example:%20Hello,%20RSyntaxTextArea

Then, run it by addint the jar to your classpath:

    java -cp rsyntaxtextarea-2.5.7.jar TextEditorDemo

More information about running Java applications can be found on Oracle's site, for example:

https://docs.oracle.com/javase/tutorial/getStarted/cupojava/win32.html

Hope this helps!
