### ISSUE TITLE
SyntaxHighlighting Issue

### ISSUE THREAD

**Issue by MaToxZ** [bobbylight/RSyntaxTextArea#169]
Hi guys, I'm trying to add a new syntax Highlighting to my own lenguajes, but I'm getting an "java.lang.InstantiationException Java Exception" and I'm not sure why, I used one of the examples as templates, I just changes my reserved words and functions, but I don't know if something is wrong with the example, because I had to change a lot of things in the code to get this work, seems like something about the version of the example and the currently version troubles, I'll put my class and the error I'm getting, to see if anyone of you can help me to find the problem.

This is how I set the new SyntaxStyle on my main class 

`Code:
      JPanel cp = new JPanel(new BorderLayout());

      RSyntaxTextArea textArea = new RSyntaxTextArea(20, 60);
      AbstractTokenMakerFactory atmf = (AbstractTokenMakerFactory)TokenMakerFactory.getDefaultInstance();
      atmf.putMapping("text/proyectoLC", "ProyectoSyntaxTokenMaker");
      textArea.setSyntaxEditingStyle("text/proyectoLC");
      /*textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);*/
      textArea.setCodeFoldingEnabled(true);
      RTextScrollPane sp = new RTextScrollPane(textArea);
      cp.add(sp);

      setContentPane(cp);
      setTitle("Text Editor Demo");
      setDefaultCloseOperation(EXIT_ON_CLOSE);
      pack();
      setLocationRelativeTo(null);`

and this is my SyntaxTokenMaker class to my new custom lenguage

`     import javax.swing.text.Segment;
      import org.fife.ui.rsyntaxtextarea.AbstractTokenMaker;
      import org.fife.ui.rsyntaxtextarea.RSyntaxUtilities;
      import org.fife.ui.rsyntaxtextarea.TokenImpl;
      import org.fife.ui.rsyntaxtextarea.TokenMap;
      import org.fife.ui.rsyntaxtextarea.TokenTypes;

      public abstract class ProyectoSyntaxTokenMaker extends AbstractTokenMaker {

	protected final String operators = "=|><&";
	protected final String separators = "()[]";
	protected final String separators2 = ".,;";			// Characters you don't want syntax highlighted but separate identifiers.
	protected final String shellVariables = "#-?$!*@_";	// Characters that are part of "$<char>" shell variables; e.g., "$_".

	private int currentTokenStart;
	private int currentTokenType;

	/**
	 * Constructor.
	 */
	public ProyectoSyntaxTokenMaker() {
		super();	// Initializes tokensToHighlight.
	}

	/**
	 * Checks the token to give it the exact ID it deserves before
	 * being passed up to the super method.
	 *
	 * @param segment <code>Segment</code> to get text from.
	 * @param start Start offset in <code>segment</code> of token.
	 * @param end End offset in <code>segment</code> of token.
	 * @param tokenType The token's type.
	 * @param startOffset The offset in the document at which the token occurs.
	 */
	@Override
	public void addToken(Segment segment, int start, int end, int tokenType, int startOffset) {

		switch (tokenType) {
			// Since reserved words, functions, and data types are all passed into here
			// as "identifiers," we have to see what the token really is...
			case TokenTypes.IDENTIFIER:
				int value = wordsToHighlight.get(segment, start,end);
				if (value!=-1)
					tokenType = value;
				break;
			case TokenTypes.WHITESPACE:
			case TokenTypes.SEPARATOR:
			case TokenTypes.OPERATOR:
			case TokenTypes.LITERAL_NUMBER_DECIMAL_INT:
			case TokenTypes.LITERAL_STRING_DOUBLE_QUOTE:
			case TokenTypes.LITERAL_CHAR:
			case TokenTypes.LITERAL_BACKQUOTE:
			case TokenTypes.COMMENT_EOL:
			case TokenTypes.PREPROCESSOR:
			case TokenTypes.VARIABLE:
				break;

			default:
				tokenType = TokenTypes.IDENTIFIER;
				break;

		}

		super.addToken(segment, start, end, tokenType, startOffset);

	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String[] getLineCommentStartAndEnd(int languageIndex) {
		return new String[] { "#", null };
	}

	/**
	 * Returns whether tokens of the specified type should have "mark
	 * occurrences" enabled for the current programming language.
	 *
	 * @param type The token type.
	 * @return Whether tokens of this type should have "mark occurrences"
	 *         enabled.
	 */
	@Override
	public boolean getMarkOccurrencesOfTokenType(int type) {
		return type==TokenTypes.IDENTIFIER || type==TokenTypes.VARIABLE;
	}

	/**
	 * Returns the words to highlight for UNIX shell scripts.
	 *
	 * @return A <code>TokenMap</code> containing the words to highlight for
	 *         UNIX shell scripts.
	 * @see org.fife.ui.rsyntaxtextarea.AbstractTokenMaker#getWordsToHighlight
	 */
	@Override
	public TokenMap getWordsToHighlight() {

		TokenMap tokenMap = new TokenMap();

		int reservedWord = TokenTypes.RESERVED_WORD;
		tokenMap.put("Caso",				reservedWord);
                tokenMap.put("Opcion",				reservedWord);
                tokenMap.put("Por Defecto",				reservedWord);
		tokenMap.put("Repetir",				reservedWord);
		tokenMap.put("Sino Si",				reservedWord);
		tokenMap.put("Sino",				reservedWord);
		tokenMap.put("Para",				reservedWord);
		tokenMap.put("Si",				reservedWord);
		tokenMap.put("Termina",			reservedWord);
		tokenMap.put("Mientras",			reservedWord);

		int function = TokenTypes.FUNCTION;
		tokenMap.put("Escribir",			function);
		tokenMap.put("Leer",			function);
                tokenMap.put("Inicio",			function);
                tokenMap.put("Fin",			function);

		return tokenMap;

	}

	/**
	 * Returns a list of tokens representing the given text.
	 *
	 * @param text The text to break into tokens.
	 * @param startTokenType The token with which to start tokenizing.
	 * @param startOffset The offset at which the line of tokens begins.
	 * @return A linked list of tokens representing <code>text</code>.
	 */
        @Override
	public TokenImpl getTokenList(Segment text, int startTokenType, final int startOffset) {

		resetTokenList();

		char[] array = text.array;
		int offset = text.offset;
		int count = text.count;
		int end = offset + count;

		// See, when we find a token, its starting position is always of the form:
		// 'startOffset + (currentTokenStart-offset)'; but since startOffset and
		// offset are constant, tokens' starting positions become:
		// 'newStartOffset+currentTokenStart' for one less subraction operation.
		int newStartOffset = startOffset - offset;

		currentTokenStart = offset;
		currentTokenType  = startTokenType;
		boolean backslash = false;

                     //beginning:
		  for (int i=offset; i<end; i++) {

			char c = array[i];

			switch (currentTokenType) {

				case TokenTypes.NULL:

					currentTokenStart = i;	// Starting a new token here.

					switch (c) {

						case ' ':
						case '\t':
							currentTokenType = TokenTypes.WHITESPACE;
							break;

						case '`':
							if (backslash) { // Escaped back quote => call '`' an identifier..
								addToken(text, currentTokenStart,i, TokenTypes.IDENTIFIER, newStartOffset+currentTokenStart);
								backslash = false;
							}
							else {
								currentTokenType = TokenTypes.LITERAL_BACKQUOTE;
							}
							break;

						case '"':
							if (backslash) { // Escaped double quote => call '"' an identifier..
								addToken(text, currentTokenStart,i, TokenTypes.IDENTIFIER, newStartOffset+currentTokenStart);
								backslash = false;
							}
							else {
								currentTokenType = TokenTypes.LITERAL_STRING_DOUBLE_QUOTE;
							}
							break;

						case '\'':
							if (backslash) { // Escaped single quote => call '\'' an identifier.
								addToken(text, currentTokenStart,i, TokenTypes.IDENTIFIER, newStartOffset+currentTokenStart);
								backslash = false;
							}
							else {
								currentTokenType = TokenTypes.LITERAL_CHAR;
							}
							break;

						case '\\':
							addToken(text, currentTokenStart,i, TokenTypes.IDENTIFIER, newStartOffset+currentTokenStart);
							currentTokenType = TokenTypes.NULL;
							backslash = !backslash;
							break;

						case '$':
							if (backslash) { // Escaped dollar sign => call '$' an identifier..
								addToken(text, currentTokenStart,i, TokenTypes.IDENTIFIER, newStartOffset+currentTokenStart);
								backslash = false;
							}
							else {
								currentTokenType = TokenTypes.VARIABLE;
							}
							break;

						case '#':
							backslash = false;
							currentTokenType = TokenTypes.COMMENT_EOL;
							break;

						default:
							if (RSyntaxUtilities.isDigit(c)) {
								currentTokenType = TokenTypes.LITERAL_NUMBER_DECIMAL_INT;
								break;
							}
							else if (RSyntaxUtilities.isLetter(c) || c=='/' || c=='_') {
								currentTokenType = TokenTypes.IDENTIFIER;
								break;
							}
							int indexOf = operators.indexOf(c,0);
							if (indexOf>-1) {
								addToken(text, currentTokenStart,i, TokenTypes.OPERATOR, newStartOffset+currentTokenStart);
								currentTokenType = TokenTypes.NULL;
								break;
							}
							indexOf = separators.indexOf(c,0);
							if (indexOf>-1) {
								addToken(text, currentTokenStart,i, TokenTypes.SEPARATOR, newStartOffset+currentTokenStart);
								currentTokenType = TokenTypes.NULL;
								break;
							}
							indexOf = separators2.indexOf(c,0);
							if (indexOf>-1) {
								addToken(text, currentTokenStart,i, TokenTypes.IDENTIFIER, newStartOffset+currentTokenStart);
								currentTokenType = TokenTypes.NULL;
								break;
							}
							else {
								currentTokenType = TokenTypes.IDENTIFIER;
								break;
							}

					} // End of switch (c).

					break;

				case TokenTypes.WHITESPACE:

					switch (c) {

						case ' ':
						case '\t':
							break;	// Still whitespace.

						case '\\':
							addToken(text, currentTokenStart,i-1, TokenTypes.WHITESPACE, newStartOffset+currentTokenStart);
							addToken(text, i,i, TokenTypes.IDENTIFIER, newStartOffset+i);
							currentTokenType = TokenTypes.NULL;
							backslash = true; // Previous char whitespace => this must be first backslash.
							break;

						case '`': // Don't need to worry about backslashes as previous char is space.
							addToken(text, currentTokenStart,i-1, TokenTypes.WHITESPACE, newStartOffset+currentTokenStart);
							currentTokenStart = i;
							currentTokenType = TokenTypes.LITERAL_BACKQUOTE;
							backslash = false;
							break;

						case '"': // Don't need to worry about backslashes as previous char is space.
							addToken(text, currentTokenStart,i-1, TokenTypes.WHITESPACE, newStartOffset+currentTokenStart);
							currentTokenStart = i;
							currentTokenType = TokenTypes.LITERAL_STRING_DOUBLE_QUOTE;
							backslash = false;
							break;

						case '\'': // Don't need to worry about backslashes as previous char is space.
							addToken(text, currentTokenStart,i-1, TokenTypes.WHITESPACE, newStartOffset+currentTokenStart);
							currentTokenStart = i;
							currentTokenType = TokenTypes.LITERAL_CHAR;
							backslash = false;
							break;
						
						case '$': // Don't need to worry about backslashes as previous char is space.
							addToken(text, currentTokenStart,i-1, TokenTypes.WHITESPACE, newStartOffset+currentTokenStart);
							currentTokenStart = i;
							currentTokenType = TokenTypes.VARIABLE;
							backslash = false;
							break;

						case '#':
							addToken(text, currentTokenStart,i-1, TokenTypes.WHITESPACE, newStartOffset+currentTokenStart);
							currentTokenStart = i;
							currentTokenType = TokenTypes.COMMENT_EOL;
							break;

						default:	// Add the whitespace token and start anew.

							addToken(text, currentTokenStart,i-1, TokenTypes.WHITESPACE, newStartOffset+currentTokenStart);
							currentTokenStart = i;

							if (RSyntaxUtilities.isDigit(c)) {
								currentTokenType = TokenTypes.LITERAL_NUMBER_DECIMAL_INT;
								break;
							}
							else if (RSyntaxUtilities.isLetter(c) || c=='/' || c=='_') {
								currentTokenType = TokenTypes.IDENTIFIER;
								break;
							}
							int indexOf = operators.indexOf(c,0);
							if (indexOf>-1) {
								addToken(text, i,i, TokenTypes.OPERATOR, newStartOffset+i);
								currentTokenType = TokenTypes.NULL;
								break;
							}
							indexOf = separators.indexOf(c,0);
							if (indexOf>-1) {
								addToken(text, i,i, TokenTypes.SEPARATOR, newStartOffset+i);
								currentTokenType = TokenTypes.NULL;
								break;
							}
							indexOf = separators2.indexOf(c,0);
							if (indexOf>-1) {
								addToken(text, i,i, TokenTypes.IDENTIFIER, newStartOffset+i);
								currentTokenType = TokenTypes.NULL;
								break;
							}
							else {
								currentTokenType = TokenTypes.IDENTIFIER;
							}

					} // End of switch (c).

					break;

				default: // Should never happen
				case TokenTypes.IDENTIFIER:

					switch (c) {

						case ' ':
						case '\t':
							addToken(text, currentTokenStart,i-1, TokenTypes.IDENTIFIER, newStartOffset+currentTokenStart);
							currentTokenStart = i;
							currentTokenType = TokenTypes.WHITESPACE;
							break;

						case '/': // Special-case to colorize commands like "echo" in "/bin/echo"
							addToken(text, currentTokenStart,i, TokenTypes.IDENTIFIER, newStartOffset+currentTokenStart);
							currentTokenStart = i+1;
							currentTokenType = TokenTypes.NULL;
							break;

						case '`': // Don't need to worry about backslashes as previous char is space.
							addToken(text, currentTokenStart,i-1, TokenTypes.IDENTIFIER, newStartOffset+currentTokenStart);
							currentTokenStart = i;
							currentTokenType = TokenTypes.LITERAL_BACKQUOTE;
							backslash = false;
							break;

						case '"': // Don't need to worry about backslashes as previous char is non-backslash.
							addToken(text, currentTokenStart,i-1, TokenTypes.IDENTIFIER, newStartOffset+currentTokenStart);
							currentTokenStart = i;
							currentTokenType = TokenTypes.LITERAL_STRING_DOUBLE_QUOTE;
							backslash = false;
							break;

						case '\'': // Don't need to worry about backslashes as previous char is non-backslash.
							addToken(text, currentTokenStart,i-1, TokenTypes.IDENTIFIER, newStartOffset+currentTokenStart);
							currentTokenStart = i;
							currentTokenType = TokenTypes.LITERAL_CHAR;
							backslash = false;
							break;

						case '\\':
							addToken(text, currentTokenStart,i-1, TokenTypes.IDENTIFIER, newStartOffset+currentTokenStart);
							addToken(text, i,i, TokenTypes.IDENTIFIER, newStartOffset+i);
							currentTokenType = TokenTypes.NULL;
							backslash = true;
							break;

						case '$': // Don't need to worry about backslashes as previous char is non-backslash.
							addToken(text, currentTokenStart,i-1, TokenTypes.IDENTIFIER, newStartOffset+currentTokenStart);
							currentTokenStart = i;
							currentTokenType = TokenTypes.VARIABLE;
							backslash = false;
							break;
						
						case '=': // Special case here; when you have "identifier=<value>" in shell, "identifier" is a variable.
							addToken(text, currentTokenStart,i-1, TokenTypes.VARIABLE, newStartOffset+currentTokenStart);
							addToken(text, i,i, TokenTypes.OPERATOR, newStartOffset+i);
							currentTokenType = TokenTypes.NULL;
							break;

						default:
							if (RSyntaxUtilities.isLetterOrDigit(c) || c=='/' || c=='_') {
								break;	// Still an identifier of some type.
							}
							int indexOf = operators.indexOf(c);
							if (indexOf>-1) {
								addToken(text, currentTokenStart,i-1, TokenTypes.IDENTIFIER, newStartOffset+currentTokenStart);
								addToken(text, i,i, TokenTypes.OPERATOR, newStartOffset+i);
								currentTokenType = TokenTypes.NULL;
								break;
							}
							indexOf = separators.indexOf(c,0);
							if (indexOf>-1) {
								addToken(text, currentTokenStart,i-1, TokenTypes.IDENTIFIER, newStartOffset+currentTokenStart);
								addToken(text, i,i, TokenTypes.SEPARATOR, newStartOffset+i);
								currentTokenType = TokenTypes.NULL;
								break;
							}
							indexOf = separators2.indexOf(c,0);
							if (indexOf>-1) {
								addToken(text, currentTokenStart,i-1, TokenTypes.IDENTIFIER, newStartOffset+currentTokenStart);
								addToken(text, i,i, TokenTypes.IDENTIFIER, newStartOffset+i);
								currentTokenType = TokenTypes.NULL;
								break;
							}
							// Otherwise, we're still an identifier (?).

					} // End of switch (c).

					break;

				case TokenTypes.LITERAL_NUMBER_DECIMAL_INT:

					switch (c) {

						case ' ':
						case '\t':
							addToken(text, currentTokenStart,i-1, TokenTypes.LITERAL_NUMBER_DECIMAL_INT, newStartOffset+currentTokenStart);
							currentTokenStart = i;
							currentTokenType = TokenTypes.WHITESPACE;
							break;

						case '`': // Don't need to worry about backslashes as previous char is space.
							addToken(text, currentTokenStart,i-1, TokenTypes.LITERAL_NUMBER_DECIMAL_INT, newStartOffset+currentTokenStart);
							currentTokenStart = i;
							currentTokenType = TokenTypes.LITERAL_BACKQUOTE;
							backslash = false;
							break;

						case '"': // Don't need to worry about backslashes as previous char is non-backslash.
							addToken(text, currentTokenStart,i-1,TokenTypes.LITERAL_NUMBER_DECIMAL_INT, newStartOffset+currentTokenStart);
							currentTokenStart = i;
							currentTokenType =TokenTypes.LITERAL_STRING_DOUBLE_QUOTE;
							backslash = false;
							break;

						case '\'': // Don't need to worry about backslashes as previous char is non-backslash.
							addToken(text, currentTokenStart,i-1,TokenTypes.LITERAL_NUMBER_DECIMAL_INT, newStartOffset+currentTokenStart);
							currentTokenStart = i;
							currentTokenType =TokenTypes.LITERAL_CHAR;
							backslash = false;
							break;

						case '$': // Don't need to worry about backslashes as previous char is non-backslash.
							addToken(text, currentTokenStart,i-1,TokenTypes.LITERAL_NUMBER_DECIMAL_INT, newStartOffset+currentTokenStart);
							currentTokenStart = i;
							currentTokenType =TokenTypes.VARIABLE;
							backslash = false;
							break;

						case '\\':
							addToken(text, currentTokenStart,i-1,TokenTypes.LITERAL_NUMBER_DECIMAL_INT, newStartOffset+currentTokenStart);
							addToken(text, i,i,TokenTypes.IDENTIFIER, newStartOffset+i);
							currentTokenType =TokenTypes.NULL;
							backslash = true;
							break;

						default:

							if (RSyntaxUtilities.isDigit(c)) {
								break;	// Still a literal number.
							}
							int indexOf = operators.indexOf(c);
							if (indexOf>-1) {
								addToken(text, currentTokenStart,i-1,TokenTypes.LITERAL_NUMBER_DECIMAL_INT, newStartOffset+currentTokenStart);
								addToken(text, i,i,TokenTypes.OPERATOR, newStartOffset+i);
								currentTokenType =TokenTypes.NULL;
								break;
							}
							indexOf = separators.indexOf(c);
							if (indexOf>-1) {
								addToken(text, currentTokenStart,i-1,TokenTypes.LITERAL_NUMBER_DECIMAL_INT, newStartOffset+currentTokenStart);
								addToken(text, i,i,TokenTypes.SEPARATOR, newStartOffset+i);
								currentTokenType =TokenTypes.NULL;
								break;
							}
							indexOf = separators2.indexOf(c);
							if (indexOf>-1) {
								addToken(text, currentTokenStart,i-1,TokenTypes.LITERAL_NUMBER_DECIMAL_INT, newStartOffset+currentTokenStart);
								addToken(text, i,i,TokenTypes.IDENTIFIER, newStartOffset+i);
								currentTokenType =TokenTypes.NULL;
								break;
							}

							// Otherwise, remember this was a number and start over.
							addToken(text, currentTokenStart,i-1,TokenTypes.LITERAL_NUMBER_DECIMAL_INT, newStartOffset+currentTokenStart);
							i--;
							currentTokenType =TokenTypes.NULL;

					} // End of switch (c).

					break;
				
                                case TokenTypes.VARIABLE:

					// Note that we first arrive here AFTER the '$' character.
					// First check if the variable name is enclosed in '{' and '}' characters.
					if (c=='{') {
						while (++i<end) {
							if (array[i]=='}') {
								addToken(text, currentTokenStart,i,TokenTypes.VARIABLE, newStartOffset+currentTokenStart);
								currentTokenType =TokenTypes.NULL;
								break;
							}
						} // End of while (++i<end).
						if (i==end) { // Happens when '}' wasn't found...
							addToken(text, currentTokenStart,end-1,TokenTypes.VARIABLE, newStartOffset+currentTokenStart);
							currentTokenType =TokenTypes.NULL;
						}
						break;
					} // End of if (i<end-1 && array[i+1]=='{').

					// If we didn't find the '{' character, find the end of the variable...
					while (i<end) {
						c = array[i];	// Not needed the first iteration, but can't think of a better way to do it...
						if (!RSyntaxUtilities.isLetterOrDigit(c) && shellVariables.indexOf(c)==-1 && c!='_') {
							addToken(text, currentTokenStart,i-1,TokenTypes.VARIABLE, newStartOffset+currentTokenStart);
							i--;
							currentTokenType =TokenTypes.NULL;
							break;
						}
						i++;
					}
								
					// This only happens if we never found the end of the variable in the loop above.
					if (i==end) {
						addToken(text, currentTokenStart,i-1,TokenTypes.VARIABLE, newStartOffset+currentTokenStart);
						currentTokenType =TokenTypes.NULL;
					}
								
					break;

                                case TokenTypes.COMMENT_EOL:
					// If we got here, then the line != "#" only, so check for "#!".
					if (c=='!')
						currentTokenType =TokenTypes.PREPROCESSOR;
					i = end - 1;
					addToken(text, currentTokenStart,i, currentTokenType, newStartOffset+currentTokenStart);
					// We need to set token type to null so at the bottom we don't add one more token.
					currentTokenType =TokenTypes.NULL;
					
					break;

                                case TokenTypes.LITERAL_CHAR:

						if (c=='\\') {
							backslash = !backslash; // Okay because if we got in here, backslash was initially false.
						}
						else {
							if (c=='\'' && !backslash) {
								addToken(text, currentTokenStart,i,TokenTypes.LITERAL_CHAR, newStartOffset+currentTokenStart);
								currentTokenStart = i + 1;
								currentTokenType =TokenTypes.NULL;
								// backslash is definitely false when we leave.
							}

							backslash = false; // Need to set backslash to false here as a character was typed.

						}
						// Otherwise, we're still an unclosed char literal...

						break;

                                case TokenTypes.LITERAL_BACKQUOTE:

						switch (c) {
								
							case '\\':
								backslash = !backslash;
								break;
								
							case '`':
								if (!backslash) {
									addToken(text, currentTokenStart,i,TokenTypes.LITERAL_BACKQUOTE, newStartOffset+currentTokenStart);
									currentTokenType =TokenTypes.NULL;
									// backslash is definitely false when we leave.
									break;
								}
								backslash = false;
								break;
							
							// Variable in the backquote string...
							case '$':

								if (backslash==true) {
									backslash = false;
									break;
								}
							
								// Add the string up-to the variable.
								addToken(text, currentTokenStart,i-1,TokenTypes.LITERAL_BACKQUOTE, newStartOffset+currentTokenStart);
								currentTokenType =TokenTypes.VARIABLE;
								currentTokenStart = i;
								
								// First check if the variable name is enclosed in '{' and '}' characters.
								if (i<end-1 && array[i+1]=='{') {
									i++; // Now we're on the '{' char.
									while (++i<end) {
										if (array[i]=='}') {
											addToken(text, currentTokenStart,i,TokenTypes.VARIABLE, newStartOffset+currentTokenStart);
											i++;
											if (i<end) {
												c = array[i];
												if (c=='`') { // The only rub - back quote right after variable.
													addToken(text, i,i,TokenTypes.LITERAL_BACKQUOTE, newStartOffset+i);
													currentTokenType =TokenTypes.NULL;
													break;
												}
												else { // Continue on with the string.
													currentTokenStart = i;
													currentTokenType =TokenTypes.LITERAL_BACKQUOTE;
													i--;
													break;
												}
											}
											else { // i==end = "trick" this method so that the string is continued to the next line.
												currentTokenStart = i;
												currentTokenType =TokenTypes.LITERAL_BACKQUOTE;
												break; // So we don't hit the condition below.
											}
										} // End of if (array[i]=='}').
									} // End of while (++i<end).
									if (i==end) { // Happens when '}' wasn't found...
										addToken(text, currentTokenStart,end-1,TokenTypes.VARIABLE, newStartOffset+currentTokenStart);
										currentTokenStart = end; // ???
										currentTokenType =TokenTypes.LITERAL_BACKQUOTE;
										break;
									}
								} // End of if (i<end-1 && array[i+1]=='{').
								
								// If we reached the end of the variable, get out.
								if (currentTokenType==TokenTypes.NULL || currentTokenType==TokenTypes.LITERAL_BACKQUOTE)
									break;

								// If we didn't find the '{' character, find the end of the variable...
								// Increment first to skip the '$'.
								while (++i<end) {
									c = array[i];
									if (!RSyntaxUtilities.isLetterOrDigit(c) && shellVariables.indexOf(c)==-1 && c!='_') {
										addToken(text, currentTokenStart,i-1,TokenTypes.VARIABLE, newStartOffset+currentTokenStart);
										if (c=='`') { // The only rub.
											addToken(text, i,i,TokenTypes.LITERAL_BACKQUOTE, newStartOffset+i);
											currentTokenType =TokenTypes.NULL;
											break;
										}
										else {
											currentTokenStart = i;
											currentTokenType =TokenTypes.LITERAL_BACKQUOTE;
											i--;
											break;
										}
									}
								}
								
								// This only happens if we never found the end of the variable in the loop above.
								// We "trick" this method so that the backquote string token is at the end.
								if (i==end) {
									addToken(text, currentTokenStart,i-1,TokenTypes.VARIABLE, newStartOffset+currentTokenStart);
									currentTokenStart = i;
									currentTokenType =TokenTypes.LITERAL_BACKQUOTE;
								}
								
								break;
								
							// Otherwise, we're still in an unclosed string...
							default:
								backslash = false; // Need to set backslash to false here as a character was typed.

						} // End of switch (c).
				
						break;

                                case TokenTypes.LITERAL_STRING_DOUBLE_QUOTE:
				
						switch (c) {
								
							case '\\':
								backslash = !backslash;
								break;
								
							case '"':
								if (!backslash) {
									addToken(text, currentTokenStart,i,TokenTypes.LITERAL_STRING_DOUBLE_QUOTE, newStartOffset+currentTokenStart);
									currentTokenType =TokenTypes.NULL;
									// backslash is definitely false when we leave.
									break;
								}
								backslash = false;
								break;
							
							// Variable in the double-quoted string...
							case '$':
							
								if (backslash==true) {
									backslash = false;
									break;
								}
							
								// Add the string up-to the variable.
								addToken(text, currentTokenStart,i-1,TokenTypes.LITERAL_STRING_DOUBLE_QUOTE, newStartOffset+currentTokenStart);
								currentTokenType =TokenTypes.VARIABLE;
								currentTokenStart = i;
								
								// First check if the variable name is enclosed in '{' and '}' characters.
								if (i<end-1 && array[i+1]=='{') {
									i++; // Now we're on the '{' char.
									while (++i<end) {
										if (array[i]=='}') {
											addToken(text, currentTokenStart,i,TokenTypes.VARIABLE, newStartOffset+currentTokenStart);
											i++;
											if (i<end) {
												c = array[i];
												if (c=='"') { // The only rub - double-quote right after variable.
													addToken(text, i,i,TokenTypes.LITERAL_STRING_DOUBLE_QUOTE, newStartOffset+i);
													currentTokenType =TokenTypes.NULL;
													break;
												}
												else { // Continue on with the string.
													currentTokenStart = i;
													currentTokenType =TokenTypes.LITERAL_STRING_DOUBLE_QUOTE;
													i--;
													break;
												}
											}
											else { // i==end = "trick" this method so that the string is continued to the next line.
												currentTokenStart = i;
												currentTokenType =TokenTypes.LITERAL_STRING_DOUBLE_QUOTE;
												break; // So we don't hit the condition below.
											}
										} // End of if (array[i]=='}').
									} // End of while (++i<end).
									if (i==end) { // Happens when '}' wasn't found...
										addToken(text, currentTokenStart,end-1,TokenTypes.VARIABLE, newStartOffset+currentTokenStart);
										currentTokenStart = end; // ???
										currentTokenType =TokenTypes.LITERAL_STRING_DOUBLE_QUOTE;
										break;
									}
								} // End of if (i<end-1 && array[i+1]=='{').
								
								// If we reached the end of the variable, get out.
								if (currentTokenType==TokenTypes.NULL || currentTokenType==TokenTypes.LITERAL_STRING_DOUBLE_QUOTE)
									break;

								// If we didn't find the '{' character, find the end of the variable...
								// Increment first to skip the '$'.
								while (++i<end) {
									c = array[i];
									if (!RSyntaxUtilities.isLetterOrDigit(c) && shellVariables.indexOf(c)==-1 && c!='_') {
										addToken(text, currentTokenStart,i-1,TokenTypes.VARIABLE, newStartOffset+currentTokenStart);
										if (c=='"') { // The only rub.
											addToken(text, i,i,TokenTypes.LITERAL_STRING_DOUBLE_QUOTE, newStartOffset+i);
											currentTokenType =TokenTypes.NULL;
											break;
										}
										else {
											currentTokenStart = i;
											currentTokenType =TokenTypes.LITERAL_STRING_DOUBLE_QUOTE;
											i--;
											break;
										}
									}
								}
								
								// This only happens if we never found the end of the variable in the loop above.
								// We "trick" this method so that the double-quote string token is at the end.
								if (i==end) {
									addToken(text, currentTokenStart,i-1,TokenTypes.VARIABLE, newStartOffset+currentTokenStart);
									currentTokenStart = i;
									currentTokenType =TokenTypes.LITERAL_STRING_DOUBLE_QUOTE;
								}
								
								break;
								
							// Otherwise, we're still in an unclosed string...
							default:
								backslash = false; // Need to set backslash to false here as a character was typed.

						} // End of switch (c).
				
						break;

			} // End of switch (currentTokenType).

		} // End of for (int i=offset; i<end; i++).

		switch (currentTokenType) {

			// Remember what token type to begin the next line with.
                    case TokenTypes.LITERAL_BACKQUOTE:
                    case TokenTypes.LITERAL_STRING_DOUBLE_QUOTE:
                    case TokenTypes.LITERAL_CHAR:
						addToken(text, currentTokenStart,end-1, currentTokenType, newStartOffset+currentTokenStart);
						break;

			// Do nothing if everything was okay.
                    case TokenTypes.NULL:
			 			addNullToken();
						break;

			// All other token types don't continue to the next line...
			default:
						addToken(text, currentTokenStart,end-1, currentTokenType, newStartOffset+currentTokenStart);
						addNullToken();

		}

		// Return the first token in our linked list.
		return firstToken;

	}

}`

The java Exception I'm getting is this:

> java.lang.InstantiationException
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)

and It references this line:
`textArea.setSyntaxEditingStyle("text/proyectoLC");`

**Comment by bobbylight** [comment]
Are you following these steps to wire your ProyectoSyntaxTokenMaker in?

[Adding Syntax Highlighting for a new Language - plugging your TokenMaker into an application](https://github.com/bobbylight/RSyntaxTextArea/wiki/Adding%20Syntax%20Highlighting%20for%20a%20new%20Language#plugging-your-tokenmaker-into-an-application)

If you are, please provide the full stack trace you get, not just the first line.  A java.lang.InstantiationException likely implies either you aren't wiring in your TokenMaker as described above, the class isn't on the classpath, or it is throwing some other Exception when trying to intantiate an instance of your TokenMaker.

**Comment by bobbylight** [comment]
Closing; the explanation is likely in my comment on May 3 above, and MaToxZ hasn't responded.
