### ISSUE TITLE
emot icons support

### ISSUE THREAD

**Issue by razakpm** [bobbylight/RSyntaxTextArea#170]
I like to use RSyntaxTextArea for developer chatting , I need all the syntax highlighting , folding etc..., also I need to support emot-icons (emoji, at least smileys ) what is the way to do this?

Also I like to show images from links , I know this is not designed for that purpose , but is it possible?

**Comment by bobbylight** [comment]
Sorry, this isn't possible.  You can build it though with JEditorPane (or JTextPane?).  I know because I did it many moons ago.  :)
