### ISSUE TITLE
Changing colors of the textarea and scroll bar

### ISSUE THREAD

**Issue by ftomassetti** [bobbylight/RSyntaxTextArea#186]
I would like to change the color of the border around the text area and the color of the scroll bar.
Any idea how to do that?

![kanvas_134](https://cloud.githubusercontent.com/assets/439078/16545601/269fc1ce-4130-11e6-8b51-0742309b010e.png)

**Comment by bobbylight** [comment]
For the scroll bar, you have to write a custom ScrollBarUI.  See [here](http://stackoverflow.com/questions/8208508/custom-design-jscollpane-java-swing) for some discussion about it.

The border around the text area is likely rendered by the encompassing JScrollPane, or *possibly* the JViewport or even JTabbedPane containing it.  Some JComponent in the hierarchy probably has an empty-ish, 1-pixel border around its content.  In my experience, the simplest way to identify the component is to call `setBackground(Color.RED)` (for example) on components, with random colors, until you see the border change color; then you know what to change.

**Comment by ftomassetti** [comment]
thanks!
