### ISSUE TITLE
Undo stack can grow unbounded

### ISSUE THREAD

**Issue by pmouawad** [bobbylight/RSyntaxTextArea#19]
Hello,
We use your nice project in jmeter.
We had a bug reported which leads to OutOfMemoryError, see this for more details:
- https://issues.apache.org/bugzilla/show_bug.cgi?id=55591

See screenshots of analysis:
![screen shot 2013-09-24 at 23 36 05](https://f.cloud.github.com/assets/3127467/1204269/93fac4b4-2561-11e3-909c-d44fcddf8f4e.png)
![screen shot 2013-09-24 at 23 35 07](https://f.cloud.github.com/assets/3127467/1204271/9a93dbe4-2561-11e3-9a5d-d2b9df95d5a7.png)

**Comment by pmouawad** [comment]
Hi,
We have a bug report on JMeter:
https://issues.apache.org/bugzilla/show_bug.cgi?id=57440
In JMeter LoggerPanel we want to disable Undo so we have overriden createUndoManager as per your tip:
https://github.com/apache/jmeter/blob/trunk/src/core/org/apache/jmeter/gui/util/JSyntaxTextArea.java
But this doesn't work as createUndoManager is called before disableUndo is initialized to true.
And unfortunately we cannot access undoManager from our subclass.
I see discardAllEdits() recreates undoManager, so:
1/ is it a reasonable fix to call discardAllEdits() in JSyntaxtTextArea constructor?
2/ or is there a better method 
3/ Or could you make undoManager accessible to subclasses through a protected getter ?

Thanks for help
Regards
Philippe M.

**Comment by pmouawad** [comment]
But if I call discardAllEdits(), I am not sure fix would survive upgrades as I see this.:
	/*
	 * NOTE:  For some reason, it appears I have to create an entirely new
	 *        <code>undoManager</code> for undo/redo to continue functioning
	 *        properly; if I don't, it only ever lets you do one undo.  Not
	 *        too sure why this is...
	 */
	public void discardAllEdits() {
		undoManager.discardAllEdits();
		getDocument().removeUndoableEditListener(undoManager);
		undoManager = createUndoManager();
		getDocument().addUndoableEditListener(undoManager);
		undoManager.updateActions();
	}

Another option would be in our createUndoManager() to retain a reference on undoManager and in constructor call undoManager#setLimit .
But those options do not look clean to me :-( 

Maybe 3/ is the cleanest one.

**Comment by bobbylight** [comment]
New suggested workarounds at #99.
