### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by kovica** [bobbylight/RSyntaxTextArea#192]
Hi!

I'm sorry I'm posting this here, but the forums (http://www.fifesoft.com/forum/) are not working. I'm getting 404.
Is there a way to disable default keyboard shortcuts?
I'm doing it like this (textArea is RSyntaxTextArea):
```
ActionMap actionMap = textArea.getActionMap();
// get the last action map, that does not have a parent. Found out that this is the one holding all the actions from RSyntaxTextArea
        while (true) {
            if (actionMap.getParent() == null) {
                break;
            }
            
            actionMap = actionMap.getParent();
        }
        
// RTA.DumbCompleteWordAction is the action linked to CRTL - ENTER
        Object keys[] = actionMap.allKeys();
        Object keyToRemove = null;
        for (Object key : keys) {
            if (key.toString().equals("RTA.DumbCompleteWordAction") == true) {
                keyToRemove = key;
                break;
            }
        }

        if (keyToRemove != null) {
            actionMap.remove(keyToRemove);
        }
```

I just want to disable CTRL-ENTER shortcut.

Thanks and best regards,
    Kovi

**Comment by bobbylight** [comment]
Yes, that's one way to do it.  You either have to remove the actual action from RSTA's ActionMap, or remove the key-to-action-name mapping from its InputMap.  The latter is the more typical approach, and is described here:

http://stackoverflow.com/questions/25727871/remove-enter-key-binding-in-jtable

(The example there is not specific to JTable, it can be applied to any JComponent).  `JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT` is indeed _usually_ the InputMap you want to modify.
