### ISSUE TITLE
Wrong detection of bracket position when is using CRLF in RDocument

### ISSUE THREAD

**Issue by chrisbln** [bobbylight/RSyntaxTextArea#194]
When I am using CRLF in a RDocument then a bracket at the end of line won't be found correctly.

Following source code in RSntaxUtilities.getMatchingBracketPosition:
int caretPosition = textArea.getCaretPosition() - 1;
bracket  = doc.charAt(caretPosition);  <- wrong character

When is using /r/n on the last caret position then I get /r instead of the braket.

**Comment by bobbylight** [comment]
Like all JTextComponents, RSTA expects it's content to always be line
feed-separated only, no carriage returns. Please ensure this is the case
before inserting text via insert() or append(), or use something like the
read() method to read from a reader or stream, which will normalize
newlines automatically.

Sent from my Nexus 6p

On Aug 16, 2016 4:30 AM, "chrisbln" <notifications@github.com> wrote:
>
> When I am using CRLF in a RDocument then a bracket at the end of line
won't be found correctly.
>
> Following source code in RSntaxUtilities.getMatchingBracketPosition:
> int caretPosition = textArea.getCaretPosition() - 1;
> bracket = doc.charAt(caretPosition); <- wrong character
>
> When is using /r/n on the last caret position then I get /r instead of
the braket.
