### ISSUE TITLE
sets gutter to row header when is enabling fold indicator (or similar properties)

### ISSUE THREAD

**Issue by chrisbln** [bobbylight/RSyntaxTextArea#196]
Gutter on line 984:
else if (RSyntaxTextArea.CODE_FOLDING_PROPERTY.equals(name)) {
...
}

After component (e. g. folderIndicator) is added to gutter, the gutter must may be set to ScrollPane.setRowHeaderView. Because previous state was gutter.getComponentCount() == 0

**Comment by bobbylight** [comment]
I'm sorry, I'm having trouble understanding the issue.  Can you provide a small example program?

**Comment by bobbylight** [comment]
Closing due to no response, but please reopen with more details if you still need this looked at
