### ISSUE TITLE
Sometimes I can't type

### ISSUE THREAD

**Issue by stefan-reich** [bobbylight/RSyntaxTextArea#197]
I'm really not sure about when this one happens. Sometimes I just can't type in a RSyntaxTextArea (no response to keys).
I create another RSyntaxTextArea in the same program - problem persists.
I start a new Java VM - problem solved.
I'd really like to make this work, as it is such a nice component!

My code is [here](http://tinybrain.de/1004360). To test, run [this](http://tinybrain.de/x30.jar), click on any item in the list and click "Edit JavaX".

**Comment by bobbylight** [comment]
Two guesses:

* All Swing UI manipulation should be done on the EDT, it doesn't look like you're doing that?
* Are you using the AutoComplete add-on library?  At one point there were issues with actions mapped to keys being removed and not added back when showing the code completion popup and hiding it in certain ways.  But, AFAIK those bugs are long gone, and it doesn't appear that you're using AutoComplete.

**Comment by stefan-reich** [comment]
Thanks, I'll look into that

Am 11.09.2016 06:10 schrieb "bobbylight" <notifications@github.com>:

**Comment by rednoah** [comment]
I can confirm that there is such an issue. Mostly when opening the dialog that contains the `RSyntaxTextArea` and if `setText` is called programmatically it usually becomes editable again and behaves normally.

EDT issues were my first guess as well, but I haven't found anything. Also hard to reproduce. It's quite rare in my case.

**Comment by stefan-reich** [comment]
...and it's back! This time in a JInternalFrame, and I think I can reproduce it too.

**Comment by stefan-reich** [comment]
OK, I'm investigating. I added a KeyListener to the text area, and it does receive key events. Just no characters appear.

**Comment by stefan-reich** [comment]
OK, so I have my bug reproducible every time. I have a simple RSyntaxTextArea in an RTextScrollPane in a JInternalFrame in a JDesktopPane where I can't type.

What can I add to the code to investigate?

**Comment by bobbylight** [comment]
@stefan-reich, are you using the AutoComplete library too? I'm awfully suspicious of it since it intercepts key events and mucks with input maps.

**Comment by stefan-reich** [comment]
For a second I was like: Oh yeah, that might be it... but then I realized I'm not using AutoComplete in the test program, and it still doesn't work.

[Here's](http://tinybrain.de/1016121) the code in my special dialect. It really doesn't do much except make a RSyntaxTextArea.

I guess I should update the library though, my version is 3.0.0-snapshot from 12/2017.
