### ISSUE TITLE
Gutter Style (enhancement)

### ISSUE THREAD

**Issue by Haeri** [bobbylight/RSyntaxTextArea#198]
I was wondering if from a technical standpoint, it would be possible to allow Gutter Styling through the xml files. Especially I would love to be able to change the **background color**.

Additionally, it would be nice to have at least some control through code over:
- Gutter border (border margin)
- Gutter font size (So that when scaling the font in the text area, the gutter font size also changes)
- Gutter font

I know it is possible to change all that when using swing components, but I am asking if this would interfere in some way with the code folding parts.

Just as a reference, here is how it can look if you allow [this](https://camo.githubusercontent.com/70c955afacddcb06a4e71dcda84cd62c05e10e73/687474703a2f2f676f696e676d616467616d65732e636f6d2f5f6f746865722f4d6f6e6f6c6974682f73637265656e3257686974652e706e67)

**Comment by bobbylight** [comment]
The only thing you want that you cannot do with theme XML today is the gutter background.  The gutter's background is always set to the text area's background in the theme XML.  The other 3 items are available; see the following in [theme.dtd](https://github.com/bobbylight/RSyntaxTextArea/blob/master/src/main/resources/org/fife/ui/rsyntaxtextarea/themes/theme.dtd#L59):

```dtd
<!ATTLIST gutterBorder
      color      CDATA #REQUIRED>
<!ATTLIST lineNumbers
      fg         CDATA #REQUIRED
      fontFamily CDATA #IMPLIED
      fontSize   CDATA #IMPLIED>
```

Ah, I see now you likely want to change the gutter margin size, not color - if so, you cannot do that yet either.

**Comment by Haeri** [comment]
Ah cool. i just found it. I was using setFont() instead of setLineNumberFont(). 
Yes I would love to change the margin. Not the margin color. I saw you have a public setGutterBorder(), but which unfortunately only accepts a GutterBorder which is private :/ 
Also changing the background color through the XML would be fantastic!

PS: Would it be possible to PM you? I have a few questions I would love to discuss with you.

**Comment by Haeri** [comment]
I finally got around actually configuring this project properly and managed to do all the changes I request above by myself. Now I created a new branch called "GutterBackground", but I have no permission to commit anything in there. So how should I proceed? it's the first time for me doing this :P

**Comment by Haeri** [comment]
Cool! Thanks for merging :D

**Comment by bobbylight** [comment]
@Haeri, no problem.  My turnaround time has been slow lately, so thanks for the pull request!
