### ISSUE TITLE
Custom tokenmaker hangs with overridden isIdentifierChar()

### ISSUE THREAD

**Issue by tttwang23** [bobbylight/RSyntaxTextArea#204]
This token maker causes the editor to hang when typing the word "abc" into an empty editor panel and double-clicking on it.  With the method isIdentifierChar() removed from the class then the editor no longer hangs with double-click.  (rsyntaxtextarea-2.6.0 SNAPSHOT)  JDK 1.8.0_102

In my data file definition the payee field could contain space characters, and I intended to use the identifier type for the payee field.

public class CashFlowTokenMaker extends TokenMakerBase
{

    public CashFlowTokenMaker()
    {
        super();
    }

    /**
     * Returns the closest {@link TokenTypes "standard" token type} for a given
     * "internal" token type (e.g. one whose value is less than 0).
     *
     * @param type The token type.
     * @return The closest "standard" token type.  If a mapping is not defined
     *         for this language, then <code>type</code> is returned.
     */
    @Override
    public int getClosestStandardTokenTypeForInternalType(final int type)
    {
        return type;
    }

    /**
     * Returns whether this programming language uses curly braces to denote code blocks.
     */
    @Override
    public boolean getCurlyBracesDenoteCodeBlocks(int languageIndex)
    {
        return true;
    }

    /**
     * Returns the text to place at the beginning and end of a line to comment it.
     */
    @Override
    public String[] getLineCommentStartAndEnd(int languageIndex)
    {
        final String[] commentBox = { "# ", "\n"};
        return commentBox;
    }

    /**
     * Returns an action to handle "insert break" key presses.
     */
    @Override
    public Action getInsertBreakAction()
    {
        return null;
    }

    /**
     * If a line ends in the specified token, this method returns whether
     * a new line inserted after that line should be indented.
     */
    @Override
    public boolean getShouldIndentNextLineAfter(final Token token)
    {
        return false;
    }

    /**
     * Returns whether this language is a markup language.
     */
    @Override
    public boolean isMarkupLanguage()
    {
        return false;
    }

    /**
     * Add a token to the current line.  No action is performed if
     * the length of the token is less than one.
     *
     * @param len the length of the specified token
     * @param pos the cursor position on current line
     * @param text the current text segment
     * @param tokenTYpe the token type
     * @param docOffset the document offset at the start of the line
     */
    void addToken(int len, int pos, Segment text, int tokenType, int docOffset)
    {
        // Ignore a token of length 0
        if (len > 0)
        {
            // The end parameter is inclusive, so there is an extra -1.
            addToken(text, text.offset + pos, text.offset + pos + len - 1,
                tokenType, docOffset + pos);
        }
    }
    
    /**
     * Returns the first token in the linked list of tokens generated
     * from <code>text</code>.  This method must be implemented by
     * subclasses so they can correctly implement syntax highlighting.
     *
     * @param text The text from which to get tokens.
     * @param initialTokenType The token type we should start with.
     * @param docOffset The offset into the document at which
     *        <code>text</code> starts.
     * @return The first <code>Token</code> in a linked list representing
     *         the syntax highlighted text.
     */
    public Token getTokenList(Segment text, int initialTokenType,
        int docOffset)
    {
        // current position
        int pos = 0;

        // Invalidate previous tokens.
        resetTokenList();

        // The type 'Segment' implements the 'CharSequence' interface.
        // As we obtain each parsing elements from regular expression
        // matches we need to count the length of each token and look
        // into the segment char array to form each token object.
        if (text.length() > 0)
        {
            {
                addToken(text.length(), pos, text, Token.IDENTIFIER, docOffset);
                addNullToken();
                System.out.println("ident " + " " + text.length());
                return firstToken;
            }
        }
        
        // The last token is the null token.
        addNullToken();
        // Returns the first token.
        return firstToken;
    }

    /**
     * Returns whether a character could be part of an "identifier" token
     * in a specific language.  This is used to identify such things as the
     * bounds of the "word" to select on double-clicking.
     *
     * @param languageIndex The language index the character was found in.
     * @param ch The character.
     * @return Whether the character could be part of an "identifier" token.
     */
    @Override
    public boolean isIdentifierChar(int languageIndex, char ch)
    {
        switch (ch)
        {
        case ' ': // space
        case '\n':
        case '\r':
        case '\t':
        case '(':
        case ')':
            return false;
        }
        return true;
    }

}

**Comment by bobbylight** [comment]
Thanks for the bug report!  We were using Segment as a CharacterIterator but not checking for the special "DONE" character value of 65535.  `TokenMaker` implementations shouldn't have to be aware of our parsing implementation or this value.
