### ISSUE TITLE
Add yaml syntax highlighting

### ISSUE THREAD

**Issue by bobbylight** [bobbylight/RSyntaxTextArea#212]
Like it says on the tin.

**Comment by OndrejSpanel** [comment]
What syntax highlighting should this implement? I see only comments and string highlighted, not numbers. When I switch to Json or Java style, I get numbers highlighted even with Yaml.

My YAML source looks like this:

```---
size:
- 4000.0
- 4000.0
grid: 40.0
bottomLevel: -50.0
colors:
  waterLevel: 0.0
  snowLevel: 500.0
config:
- radius:
  - 1000.0
  - 4000.0
  height:
  - 10.0
  - 200.0
  count: 0.5```
