### ISSUE TITLE
add method: setMarkOccurrencesDelay()

### ISSUE THREAD

**Issue by goranschwarz** [bobbylight/RSyntaxTextArea#218]
Hi there!

Is it possible to implement some thing like:
setMarkOccurrencesDelay()

something like the below, which is a _copy_ of setMarkOccurrencesColor()
```
public void setMarkOccurrencesDelay(int delay) {
	if (markOccurrencesSupport!=null)
		markOccurrencesSupport.setDelay(delay);
}

```

**Comment by Haeri** [comment]
Thats why I set the `void org.fife.ui.rtextarea.RTextArea.clearMarkAllHighlights()` to public in my fork :D

**Comment by bobbylight** [comment]
This was added in RSTA 2.6.0, see #177 for more information.
