### ISSUE TITLE
Menu Bar with Save Button like in your example Screenshot

### ISSUE THREAD

**Issue by shining01** [bobbylight/RSyntaxTextArea#228]
Hello,
is there a method to display the menu bar like in your example screenshots? 
If not, do you have an example? 
Thanks

**Comment by bobbylight** [comment]
Not built into the library, you have to use standard Swing for that.  Create your own `javax.swing.text.Action`, and when it's executed, use [JTextComponent.write()](http://docs.oracle.com/javase/7/docs/api/javax/swing/text/JTextComponent.html#write(java.io.Writer)) to write the text content to a file.
