### ISSUE TITLE
Binaries for 2.6.1 are missing on sourceforge

### ISSUE THREAD

**Issue by matthijskooijman** [bobbylight/RSyntaxTextArea#230]
The [tag says](https://github.com/bobbylight/RSyntaxTextArea/releases/tag/2.6.1):

> Precompiled jars are available on SourceForge and Maven (com.fifesoft:rsyntaxtextarea:2.6.1). 

However, Sourceforge only seems to have them up to 2.6.0.

**Comment by bobbylight** [comment]
Fixed, thanks.
