### ISSUE TITLE
Can't style gutter

### ISSUE THREAD

**Issue by thomasorlando** [bobbylight/RSyntaxTextArea#239]
I've created an XML theme and everything loads fine, but when I try to style the gutter, my changes don't take effect. Everything else is styled perfectly, only the gutter creates problems.

**Code**
```xml
<!-- Gutter styling. -->
<gutterBorder color="FFFFFF"/>
<lineNumbers fg="000000"/>
<foldIndicator fg="6A8088" iconBg="2f383c" iconArmedBg="3f484c"/>
<iconRowHeader activeLineRange="878787"/>
```

**Comment by Haeri** [comment]
Seems to be working fine on my end with the latest commit ([3.0.0](https://github.com/bobbylight/RSyntaxTextArea/commit/178ca9f714fd79040beea208f892963a23fed1a5))
![Screenshot](http://monolith-code.net.tiberius.sui-inter.net/Upload/Screenshot.png)

Even though I have to confess that I have no clue what `activeLineRange` actually does :S

**Comment by thomasorlando** [comment]
I'm working with the latest release version ([2.6.1](https://github.com/bobbylight/RSyntaxTextArea/releases/tag/2.6.1)).  
  
Is this a know bug?

**Comment by thomasorlando** [comment]
Found the problem. I applied the theme before adding my `RSyntaxtTextArea` to the `RTextScrollPane`. 😷  
Problem is fixed, now everything is working...
