### ISSUE TITLE
Help me to import & run the code in eclipse

### ISSUE THREAD

**Issue by hbkvikas** [bobbylight/RSyntaxTextArea#243]
Could you please help me how I can import the project and run it successfully in Eclipse.
A detailed explanation would be deeply appreciated :)

**Comment by Haeri** [comment]
It depends on what you want to do. If you want to use this repository as a library for your own project, you could simply download the [latest jar file](https://github.com/bobbylight/RSyntaxTextArea/releases) and [add it into your projects build path.](https://stackoverflow.com/questions/3280353/how-to-import-a-jar-in-eclipse) 
If you want to poke around with the code or compile the latest commit, you can [download a zip](https://github.com/bobbylight/RSyntaxTextArea/archive/master.zip) or [clone this repository](github-windows://openRepo/https://github.com/bobbylight/RSyntaxTextArea). To import into Eclipse, you can right click on your project explorer window > Import > Gradle Project and click your way through the configuration window. This should auto-magically set up the project for you.

**Comment by bobbylight** [comment]
I'm taking the liberty of closing this one, since @Haeri answered you, this question's a little old, and you have another, very similar, question [here](https://github.com/bobbylight/RSyntaxTextArea/issues/244).
