### ISSUE TITLE
Building with gradle gives error. Help me build and run it

### ISSUE THREAD

**Issue by hbkvikas** [bobbylight/RSyntaxTextArea#244]
Please help me in building and running the application

**Comment by bobbylight** [comment]
What specific error are you getting?  It should be as easy as cloning the repository and running `gradlew build`.  If this doesn't work for you, please post the specific error you're getting.

**Comment by stefan-reich** [comment]
FWIW, I had problems building the other modules (AutoComplete and RSTAUI) and had to change the gradle file a tiny bit as it didn't find my installation of RSyntaxTextArea otherwise. Not sure if this applies here.

**Comment by bobbylight** [comment]
With no response from the OP, I'm closing.  Feel free to reopen if you still have trouble.
