### ISSUE TITLE
Code folding doesn't work for Python

### ISSUE THREAD

**Issue by hbkvikas** [bobbylight/RSyntaxTextArea#245]
I tried the version 2.6.1 and apparently I found out that code folding is not working for python.

**Comment by bobbylight** [comment]
Code folding is only supported for certain languages, and Python is not one of them.  I'm tagging this as a feature request.

I don't know Python, so it's unlikely I'll work on this, but pull requests are welcome!

**Comment by bobbylight** [comment]
This feature is available on Sonatype as 3.1.0-SNAPSHOT and will be available in the 3.1.0 release soon.
