### ISSUE TITLE
Wrong squiggle position when text contains UTF-8 2-bytes or 3-bytes (ParserNotice)

### ISSUE THREAD

**Issue by maelvalais** [bobbylight/RSyntaxTextArea#246]
Hi,

I implemented the interface `ParserNotice` in order to highlight the errors produced by a compiler. The compiler returns an absolute position that **counts all 2-bytes and 3-bytes UTF-8 characters as 1-byte**.

The thing is that the function required for displaying the 'squiggling' (red underlying), `getOffset()`, seem to require the position including the 2-bytes and 3-bytes.

In the issue https://github.com/touist/touist/issues/284, I show an example.

How could I solve that? Did anyone bump into that kind of problem already?

**Note:** I don't really know how to give a minimal working example.

**Comment by bobbylight** [comment]
This is interesting; I'm surprised this bug exists.  The offset for squiggle-underlines should be in chars, which are essentially UTF code points, so double-byte chars should be fine.  I'm a little less sure about chars using more than 2 bytes, but my point is that things should be logical char-based, not byte-based.

I'll try to cobble up an example.

Do you notice odd caret behavior as well, or is it just the squiggle underlining that's broken?  I'd imagine caret movement would be broken as well if bytes-vs-chars is really a problem.

**Comment by bobbylight** [comment]
This seems to work with the following example app:

```java
package test;

import javax.swing.*;

import org.fife.ui.rsyntaxtextarea.parser.AbstractParser;
import org.fife.ui.rsyntaxtextarea.parser.DefaultParseResult;
import org.fife.ui.rsyntaxtextarea.parser.DefaultParserNotice;
import org.fife.ui.rsyntaxtextarea.parser.ParseResult;
import org.fife.ui.rtextarea.*;
import org.fife.ui.rsyntaxtextarea.*;

import java.awt.*;

public class ParserNoticeOffsetTest extends JFrame {

	private ParserNoticeOffsetTest() {

		JPanel cp = new JPanel(new BorderLayout());

		RSyntaxTextArea textArea = new RSyntaxTextArea(20, 60);
		textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
		textArea.setText(";; à\nwe are for a different for \nfor\n");
		textArea.addParser(new ForParser());
		textArea.setCodeFoldingEnabled(true);
		RTextScrollPane sp = new RTextScrollPane(textArea);
		cp.add(sp);

		setContentPane(cp);
		setTitle("Text Editor Demo");
		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		pack();
		setLocationRelativeTo(null);

	}

	public static void main(String[] args) {
		SwingUtilities.invokeLater(new Runnable() {
			public void run() {
				new ParserNoticeOffsetTest().setVisible(true);
			}
		});
	}

	/**
	 * Squiggle-underlines all instances of the keyword "for".
	 */
	private static class ForParser extends AbstractParser {

		@Override
		public ParseResult parse(RSyntaxDocument doc, String style) {

			DefaultParseResult result = new DefaultParseResult(this);

			for (Token t : doc) {
				if (t.is(TokenTypes.RESERVED_WORD, "for")) {
					int offs = t.getOffset();
					int len = t.length();
					int line = doc.getDefaultRootElement().getElementIndex(offs);
					result.addNotice(new DefaultParserNotice(this, "Keyword 'for' found", line, offs, len));
				}
			}

			return result;
		}
	}
}
```

See this screenshot:

![squiggle-underlines-working](https://user-images.githubusercontent.com/1631766/32974165-132fe1b6-cbca-11e7-94cc-c9c065a46f8a.png)

Might it be some sort of issue converting the line offset to a char offset in RSTA?

**Comment by maelvalais** [comment]
Hi,

Thank you for taking some time for this issue!! I tested your minimal working example and you are right, everything works as expected.

<details> <summary>What I had first wrote</summary>
In my project, the implemented [`AbstractParser`] (https://github.com/touist/touist/blob/master/support/gui/src/gui/editionView/editor/ErrorParser.java) is basically calling an external binary, `touist`. Each error given by `touist` contains a line number, column number and buffer offset which are in turn converted into a [`ParserNotice`](https://github.com/touist/touist/blob/master/support/gui/src/gui/editionView/editor/ErrorParserNotice.java).

But the locations returned by `touist` are char-based positions, i.e., it does not take the UTF-8 chars into account in the offsets/column numbers; for example, if an error is given for the input at character `c`:
```
à b c d
      ^
```
then
- line number given to the ParserNotice is 1
- column is 5
- buffer offset is 5

If I modify your example to add a squiggle at this location:

```java
package test;
import javax.swing.*;
import org.fife.ui.rsyntaxtextarea.parser.AbstractParser;
import org.fife.ui.rsyntaxtextarea.parser.DefaultParseResult;
import org.fife.ui.rsyntaxtextarea.parser.DefaultParserNotice;
import org.fife.ui.rsyntaxtextarea.parser.ParseResult;
import org.fife.ui.rtextarea.*;
import org.fife.ui.rsyntaxtextarea.*;
import java.awt.*;

public class ParserNoticeOffsetTest extends JFrame {

	private ParserNoticeOffsetTest() {

		JPanel cp = new JPanel(new BorderLayout());

		RSyntaxTextArea textArea = new RSyntaxTextArea(20, 60);
		textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
		textArea.setText(";; à\nwe are for a different for \nfor\n");
		textArea.addParser(new ForParser());
		textArea.setCodeFoldingEnabled(true);
		RTextScrollPane sp = new RTextScrollPane(textArea);
		cp.add(sp);

		setContentPane(cp);
		setTitle("Text Editor Demo");
		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		pack();
		setLocationRelativeTo(null);

	}

	public static void main(String[] args) {
		SwingUtilities.invokeLater(new Runnable() {
			public void run() {
				new ParserNoticeOffsetTest().setVisible(true);
			}
		});
	}

	/**
	 * Squiggle-underlines all instances of the keyword "for".
	 */
	private static class ForParser extends AbstractParser {

		@Override
		public ParseResult parse(RSyntaxDocument doc, String style) {
			DefaultParseResult result = new DefaultParseResult(this);
			result.addNotice(new DefaultParserNotice(this, "Character 'c' at offset 5", 1, 7, 3));
			return result;
		}
	}
}
``` 

then the squiggling is at the wrong position:

![wrong squiggling](https://user-images.githubusercontent.com/2195781/32981426-0b5a68b0-cc76-11e7-8c94-60e3b9eb1e54.png)


I am kind of stuck :(
 </details>

I spent 1 hour trying to reproduce the issue; and I realized everything was fine in RSTA!! My external program, `touist`, returns a wrong buffer offset, and it is the reason for all this!

I guess it has to do with the fact that `ocamllex` do not play nice with UTF-8 input...

I am sorry for the inconvenience; thank you so much for helping me find out where this "bug" was!
😄

**Comment by bobbylight** [comment]
No problem!  If you have problems on the native side, perhaps you could use Java to detect chars that are > 2 bytes in the native charset?  This may prove too difficult unless Java has an API for detecting byte count for a specific code point, for the system encoding (and you'd have to assume the system encoding unless you can assume something else like UTF-8).  Just an idea though.

Then you could convert the "column number" from a byte count to a Java char count.

Probably best if you handle it outside of Java though, like you mentioned :)
