### ISSUE TITLE
[Question] Scrolling to a specific line

### ISSUE THREAD

**Issue by tmarcoe** [bobbylight/RSyntaxTextArea#247]
I'm actually writing a stepping debugger for a new language and I want to mark the line that the debugger has stepped to. I know how to highlight the current line but can I set the editor to scroll to it?

**Comment by tmarcoe** [comment]
Never mind... I just figured it out.

**Comment by joeferner** [comment]
Can you tell us how?

**Comment by tmarcoe** [comment]
Actually, I thought I had it but the solution didn't work and I forgot to update this thread (sorry about that). I can highlight a particular line but scrolling to it seems illusive.

**Comment by joeferner** [comment]
I think I got it to work

```java
SwingUtilities.invokeLater(new Runnable() {
  @Override
  public void run() {
    int y = code.yForLine(line);
    textScrollPane.getVerticalScrollBar().setValue(y);
  }
});
```
