### ISSUE TITLE
Finding the '*/' in a multi-line comment. 

### ISSUE THREAD

**Issue by tmarcoe** [bobbylight/RSyntaxTextArea#249]
I have most of the highlighting editor working. However, since I'm writing the token marker by hand, I can't seem to be able to find the matching '*/' on a multi-line comment. There's not a lot of documentation on that and I found only 2 examples, both of which do not use multi-line comments. I can identify the tokens easily enough, but I have trouble finding where the end of the multi-line comment. Can you help me please?

**Comment by bobbylight** [comment]
I don't have any specific examples, but I'd treat it like how [UnixShellTokenMaker](https://github.com/bobbylight/RSyntaxTextArea/blob/master/src/main/java/org/fife/ui/rsyntaxtextarea/modes/UnixShellTokenMaker.java) looks for backslashes to handle escaped stuff.  Some pseudocode:

```java
switch (ch) {
   ...
   case '*':
      prevIsStar = true;
      break;
   case '/':
      if (prevIsStar) {
         // Close comment
         prevIsStar = false;
         addToken(comment token params...);
         ... etc. ...
      }
      else {
         // Still in comment
      }
      break;
```
You just need to ensure that you reset `prevIsStar` to `false` everywhere that is appropriate.
