### ISSUE TITLE
Scrollbars Don't Work (RTextScrollPane)

### ISSUE THREAD

**Issue by mearvk** [bobbylight/RSyntaxTextArea#250]
I'm not able to get the RTextScrollPane to work on even a simple example of RSyntaxTextPane.

I get no scrollbars when the text is added something like 50% of the time.  The text is clearly further down in the RTextScrollPane than the visible portion of the document.  I've tried adding the text with setText and with setDocument and neither seems to work.
```

		this.rstextpane = new RSTextPane_000(this);

		this.rstextpane.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);

		this.rstextpane.setCodeFoldingEnabled(true);

		this.rstextpane.setBackground(new Color(240,240,240));

		this.rstextpane.setCurrentLineHighlightColor(new Color(180,180,180));

		this.rstextpane.setAutoscrolls(true);

		//

		this.rstextscrollpane = new RTextScrollPane();

		this.rstextscrollpane.setViewportView(this.rstextpane);

		this.rstextscrollpane.setHorizontalScrollBarPolicy(RTextScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);

		this.rstextscrollpane.setVerticalScrollBarPolicy(RTextScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
```

The (barely) custom Superclass has: 

```
package org.widgets;

import apml.system.Apmlbasesystem;
import apml.system.bodi.Bodi;
import org.events.LoadApmlDocumentEvent;
import org.fife.ui.rsyntaxtextarea.RSyntaxDocument;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;

import javax.swing.*;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.Document;
import javax.swing.text.SimpleAttributeSet;
import java.awt.*;
import java.io.BufferedReader;
import java.io.FileReader;

public class RSTextPane_000 extends RSyntaxTextArea
{
	public String bodi = "//ui/editor/rstextpane_000";

	public Component parent;

	//
	public RSTextPane_000(Component parent)
	{
		this.parent = parent;

		try
		{
			Bodi.context("editor").put("//ui/editor/rstextpane_000", this);
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
	}

	//
	public RSTextPane_000(Component parent, Apmlbasesystem monitor)
	{
		this.parent = parent;

		try
		{
			Bodi.context("editor").put("//ui/editor/rstextpane_000", this);
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
	}

	//
	public void loaddocument(LoadApmlDocumentEvent event)
	{
		try
		{
			BufferedReader reader = new BufferedReader(new FileReader(event.file));

			String line = null;

			StringBuffer text = new StringBuffer();

			while((line=reader.readLine())!=null)
			{
				text = text.append(line+"\n");
			}

			//

			Document doc;

			doc = new RSyntaxDocument(SYNTAX_STYLE_XML);

			doc.insertString(0, text.toString(), new SimpleAttributeSet());

			//

			this.setDocument(doc);
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
	}

	@Override
	public Dimension getPreferredSize()
	{
		return new Dimension(this.parent.getWidth(), this.parent.getHeight());
	}
```

**Comment by mearvk** [comment]
Could we close this up soon?  Thx

**Comment by mearvk** [comment]
I *think* I have this solved.   If you would carefully *double check* if the RTextScrollPane does *explicitly require* an overridden getPreferredSize.  It appears this is the issue with Swing doing repainting.  

Thanks. ok.

**Comment by mearvk** [comment]
Issue that I found (quickly looking back on it) was the a Parent Class was or was not supposed to have a getPreferredSize overridden.  I have (current code as reference) that the JPanel parent *should* have an overridden impl.  /ok.

**Comment by bobbylight** [comment]
there shouldn't be a need to override `getPreferredSize()`, or call `setPreferredSize()`, on any RSTA-related component.  In general, overriding `getPreferredSize()`  in Swing is a bad idea.  It's a code smell and can lead to weird issues, perhaps that's what you're seeing here.

The easiest way to set a standard size for your text area is to use the constructor that takes a row count and column count, then put that directly into an `RTextScrollPane`, like what the example does in [README.md](https://github.com/bobbylight/RSyntaxTextArea/blob/master/README.md).

Hope this helps!

**Comment by bobbylight** [comment]
Closing as this is an old question, and looks to be a layout/application issue and not an issue with this library.
