### ISSUE TITLE
Modifying C++ syntax highlighting TokenMap

### ISSUE THREAD

**Issue by BullyWiiPlaza** [bobbylight/RSyntaxTextArea#254]
I want to customize the highlighted reserved words and functions but still re-use all of the C++ syntax highlighting logic.

I found `CPlusPlusTokenMaker` so extending seems to make sense as a first step. However, I didn't find a way to modify the `TokenMap` which is a member variable of `AbstractTokenMaker`. It appears as if `AbstractTokenMaker` is not used by the `CPlusPlusTokenMaker` (only by `WindowsBatchTokenMaker` and `UnixShellTokenMaker`). How would I implement something like the following?

```
public void updateTokenMap() {  
   tokenMap.put("foo",  Token.RESERVED_WORD);
   tokenMap.put("bar",   Token.RESERVED_WORD);
   tokenMap.remove("virtual");
  
   tokenMap.put("foobar",  Token.FUNCTION);
}
```

[This](https://github.com/bobbylight/RSyntaxTextArea/wiki/Adding-Syntax-Highlighting-for-a-new-Language) tutorial didn't explain how to modify an existing language syntax style. I do not want to implement a new one though for this "simple" change.

**Comment by bobbylight** [comment]
This is requested in feature request #2.  Also note there's a workaround in there that may work for you.
