### ISSUE TITLE
Yaml code folding

### ISSUE THREAD

**Issue by OndrejSpanel** [bobbylight/RSyntaxTextArea#255]
In continuation to #212, it would be nice to have code folding for Yaml.

I will try to provide a PR. I guess https://github.com/bobbylight/RSyntaxTextArea/wiki/Adding-Code-Folding-for-a-new-Language should be a good starting point.

**Comment by OndrejSpanel** [comment]
I have tried to implement this, I have something which is almost working, currently written is Scala:

```
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea
import org.fife.ui.rsyntaxtextarea.folding.{Fold, FoldParser, FoldType}

import scala.collection.mutable.ArrayBuffer
import scala.collection.JavaConverters._

class YamlFoldParser extends FoldParser {
  def getFolds(textArea: RSyntaxTextArea) = {
    val text = textArea.getText

    val folds = ArrayBuffer[Fold]()

    val wholeFile = new Fold(FoldType.CODE, textArea, 0)
    folds += wholeFile

    var parents = List.empty[(Int, Fold)]
    parents = 0 -> wholeFile :: parents

    var offset = 0
    var lastOffset = 0
    for (l <- text.linesWithSeparators) {
      val indent = if (l startsWith "---") 0 else {
        val content = l.dropWhile(_ == ' ').dropWhile(_ == '-')
        l.length - content.length
      }
      if (indent > parents.head._1) {
        val fold = parents.head._2.createChild(FoldType.CODE, lastOffset)
        folds += fold
        parents = indent -> fold :: parents
      } else if (indent < parents.head._1) {
        while (parents.head._1 > indent) {
          parents.head._2.setEndOffset(lastOffset)
          assert(parents.tail.nonEmpty)
          parents = parents.tail
        }
      }
      lastOffset = offset
      offset += l.length
    }

    folds.asJava
  }
}
```

The "almost" part is annoying. While folding works, editing under any folded code does not. Even with a primitive YAML file:

```
---
seed: 123456
size:
- 1000.0
- 1000.0
grid: 2.0
```
When I collapse the size region, once I click to the following line  `grid: 2.0`, it disappears. I guess my folds are wrong somehow, but I do not see how. Are there some specific rules or requirements of what should the values of `endOffs` / `startOffs` be, so that I can verify I follow them?

**Comment by OndrejSpanel** [comment]
I have abandoned the implementation above, instead I have started with `HtmlFoldParser` and I have a working version now, submitted as a PR.

**Comment by bobbylight** [comment]
The pull request has been merged, thanks!
