### ISSUE TITLE
JSON - Minor syntax highlighing issue

### ISSUE THREAD

**Issue by krishnanmms** [bobbylight/RSyntaxTextArea#256]
Syntax highlighting of JSON has minor glitch when there is a space between "key" and the colon. The attached image has lines both with a space between quote and colon and without. If there is space the key (field name) is not in the right color

"name": "Westley NORRIS", => No space, works fine
"gender" : "male",  => contains space - key is not color correctly

![json-issue](https://user-images.githubusercontent.com/21301676/36083322-1719bb0c-0fd7-11e8-9751-1ebd144dc2ea.png)

**Comment by loiclefevre** [comment]
Seems having this at line 280 of JsonTokenMaker.flex:

{Key}/([ \t\f]*):			{ addToken(Token.VARIABLE); }

instead of

{Key}/:			{ addToken(Token.VARIABLE); }

solves the problem but produces a warning by JFlex.
