### ISSUE TITLE
Font size change corrupts inactive tabs

### ISSUE THREAD

**Issue by kravlost** [bobbylight/RSyntaxTextArea#260]
[Arduino issue #7321](https://github.com/arduino/Arduino/issues/7321) highlights a problem with the fonts being corrupted in inactive tabs following a font size change. If an inactive tab hasn't been opened, the font scaling is applied; if it *has* been previously opened, the font scaling isn't applied correctly.

@facchinm describes the problem [here](https://github.com/arduino/Arduino/issues/7321#issuecomment-373041935).

**Comment by bobbylight** [comment]
@steronydh, @faccinhm, can either of you verify if this is still an issue?

Am I understanding things correctly, that to reproduce this:

* Open two RSTA instances in two tabs.  Make sure one is added to the UI but never displayed.
* Increase the font size of the not-yet-shown RSTA instance (via `setFont(Font)`?)
* Switch to the not-yet-shown RSTA
* See the font has not been updated, or not updated properly

?
