### ISSUE TITLE
Paint non existing EOL symbol

### ISSUE THREAD

**Issue by olegvasylenko** [bobbylight/RSyntaxTextArea#263]
RSyntaxTextArea paint non existing EOL symbol at the end of file. Whitespaces and EOL set to be visible.
Language Sytax: JavaScript
```
...
area.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVASCRIPT);
area.setCodeFoldingEnabled(false);
area.setEOLMarkersVisible(true);
area.setWhitespaceVisible(true);
..
```
 [Example in comparison to notepad++](https://drive.google.com/open?id=1C91ewHC3CsuXg8lxT0LyW8EmoCqYNA3i)

**Comment by bobbylight** [comment]
In RSTA, EOL markers represent the end of the line, not the line terminator character.  Thus, they are useful for visually checking whether extraneous whitespace is at the end of lines, but not to determine whether line terminators are LF or CR/LF, like in other editors like Notepad++.
