### ISSUE TITLE
Does this project have detailed documentation?

### ISSUE THREAD

**Issue by lwanqiang** [bobbylight/RSyntaxTextArea#270]
eg: i don't kown how can  i  to setting <code>null</code>

**Comment by lwanqiang** [comment]
Setting to < c o de >null< / c o d e >

**Comment by bobbylight** [comment]
Can you be more specific? What are you trying to do? A code snippet might help.

**Comment by lwanqiang** [comment]
![image](https://user-images.githubusercontent.com/25922988/41759634-0631ac4e-7622-11e8-9c01-a52fbd174d45.png)I would like to know what the role of this class is and account for too much memory. Is there a way to optimize it?

**Comment by lwanqiang** [comment]
when i run gc,the memory consumption is greatly reduced

**Comment by bobbylight** [comment]
Closing due to lack of feedback.
