### ISSUE TITLE
If UNDO'ing multiline comment, code colloring is messed up.

### ISSUE THREAD

**Issue by DPovilas** [bobbylight/RSyntaxTextArea#277]
I'm using SYNTAX_STYLE_SAS and multiline comments. If I comment some part of code and then click ctrl+z (undo), the coloring of code is messed up.

![commented_sas_code_1](https://user-images.githubusercontent.com/10043970/45357824-3281ea00-b5d0-11e8-80e8-ad3fb1f8d6c1.PNG)
![ctrl_z_is_clicked_2](https://user-images.githubusercontent.com/10043970/45357823-3281ea00-b5d0-11e8-9f7c-5a1705085fda.PNG)

**Comment by bobbylight** [comment]
Can you provide a specific set of instructions to reproduce this?  That is, what lines are commented/uncommented, and in what order?  I'm having trouble reproducing but have seem bugs like this in the past.

**Comment by DPovilas** [comment]
Actualy all steps are visible in my screenshots. Just took an example that you provided and changed language to SAS and did steps which are visible and written in my question.

**Comment by bobbylight** [comment]
I'm still having trouble reproducing this.  I've tried both:

* Adding the start `/*` at the beginning of a line, then its mathing `*/` at the end, 3 times, then ctrl+Z several times
* Adding all of the `/*` tokens at the start of the three lines to match the screenshot, l then added the three matching `*/` tokens, then ctrl+Z several times

In both cases, syntax highlighting is not messed up.  Can you clarify in what order you added the comment start- and end-delimiters?

**Comment by DPovilas** [comment]
@bobbylight I just checked my code and noticed that I forgot to mention that I've added this code at your sample code:

`textArea.setDocument(new RSyntaxDocument(SyntaxConstants.SYNTAX_STYLE_SAS) {
@Override
public String[] getLineCommentStartAndEnd(int languageIndex) {
return new String[] {"/*", "*/"};
}
});`

This code adds multiline functionality to SAS syntax. With this code I'm getting colloring error. I managed to solve it by commenting 619 line of `RsyntaxTextArea` class. The commented line is  `return line;`.

**Comment by bobbylight** [comment]
I took a simpler approach to a fix and simply changed the order that `/*` and `*/` were added on each line.  By doing them in reverse, the undos (which undo each inserted text segment individually) do not trigger all subsequent lines to be flagged as in-multi-line-comments.
