### ISSUE TITLE
How to get line number from GutterIconInfo

### ISSUE THREAD

**Issue by Erickneur** [bobbylight/RSyntaxTextArea#280]
With the following code I can get the offset of the text area to where it finds a breakpoint, but I can not calculate just the line of each breakpoint.

`GutterIconInfo[] breakPoints = gutter.getBookmarks();`
`for (GutterIconInfo breakPoint : breakPoints) {`
`          System.out.println("Break Point Marked Offset: " + breakPoint.getMarkedOffset());`
` }`

**Comment by bobbylight** [comment]
`textArea.getLineOfOffset(breakPoint.getMarkedOffset())` ?
