### ISSUE TITLE
Problem with minimalistic TokenMaker implementation

### ISSUE THREAD

**Issue by davidsusu** [bobbylight/RSyntaxTextArea#281]
My custom TokenMaker implementation displays correctly, but **editing/selection works very strangely**. I simplified my code for producing a really minimalistic example (which marks all lines as regular single-line comment regardless of their content), but the result has the strange behavior too:

```java
public class EnableTokenMaker extends TokenMakerBase {

    @Override
    public Token getTokenList(Segment segment, int startTokenType, int startOffset) {
        resetTokenList();
        if (segment.count > 0 && segment.offset + segment.count > startOffset) {
            addToken(segment, startOffset, segment.offset + segment.count - 1,
                    Token.COMMENT_KEYWORD, startOffset + startOffset - segment.offset);
        }
        addNullToken();
        return firstToken;
    }

}
```

What's wrong with my implementation? Could you provide a working minimal example (simpler and more clear than in the README).

**Comment by bobbylight** [comment]
@davidsusu, I'll try to cobble something together tonight and post it here.  I am suspicious of your `startOffset + startOffset - segment.offset` parameter.  I do know that all the params to `addToken()` are somewhat confusing.

**Comment by davidsusu** [comment]
Finally I successfully crafted a working version.

As a reference for future readers, here is an example that highlights the first five characters of each line as keyword, and the remaining part as comment:

```java
public class EnableTokenMaker extends TokenMakerBase {

    @Override
    public Token getTokenList(Segment segment, int startTokenType, int startOffset) {
        resetTokenList();

        if (segment.count > 5) {
            addToken(segment, segment.offset, segment.offset + 4, Token.RESERVED_WORD, startOffset);
            addToken(segment, segment.offset + 5, segment.offset + segment.count - 1, Token.COMMENT_KEYWORD, startOffset + 5);
        } else if (segment.count > 0) {
            addToken(segment, segment.offset, segment.offset + segment.count - 1, Token.RESERVED_WORD, startOffset);
        }
        
        addNullToken();
        return firstToken;
    }
    
}
```
