### ISSUE TITLE
breakpoint visualisation in editor 

### ISSUE THREAD

**Issue by sukh1495** [bobbylight/RSyntaxTextArea#284]
Hi 
i am using 1.5 or 1.6 version of this editor now i want to add support of breakpoint like feature for this i need to add a symbol on left side of line number like in eclipse or as seen in demo of latest jar of RSytaxTextArea Demo.

Please let me now how can i add this support in my existing version of editor without any need to re-implement my custom code  for new version.

**Comment by bobbylight** [comment]
If the version of RSTA you're using doesn't have breakpoint/per-line icon support, you can copy the implementation from a more recent version of the library (preferably preserving the license).
