### ISSUE TITLE
FileEditor Implementation

### ISSUE THREAD

**Issue by agahEbrahimi** [bobbylight/RSyntaxTextArea#285]
Hello, 

Would it be possible to only use the file editor and not the tool bars that come along side this framework? 

Thank you, 
Agah Ebrahimi

**Comment by bobbylight** [comment]
Yes, you can use just the editor component.  Check out either `RSyntaxTextArea` or `org.fife.ui.rsyntaxtextarea.TextEditorPane` if you also want file loading, saving, etc. baked into the component.  All other features are opt-in.
