### ISSUE TITLE
CSS lexer doesn't handle multiline comments

### ISSUE THREAD

**Issue by DexterHaslem** [bobbylight/RSyntaxTextArea#289]
Comments can cause tokens to throw exceptions when using the CSSTokenMaker.
Here is an example test i reproduced with, hopefully it is something trivial:

```java
    @Test
    void cssTokenizerTest()
    {
        String[] fileLines = {
        "/*! normalize.css v3.0.2 | MIT License | git.io/normalize */",
        "",
        "/**",
        " * 1. Set default font family to sans-serif.",
        " */"};

        CSSTokenMaker cssTokenMaker = new CSSTokenMaker();
        int curTokenType = TokenTypes.NULL;
        for (String line : fileLines)
        {
            Segment segment = new Segment(line.toCharArray(), 0, line.length());
            Token token = cssTokenMaker.getTokenList(segment, curTokenType, 0);
            while (token != null)
            {
                curTokenType = token.getType();
                System.out.println(token.getLexeme());
                token = token.getNextToken();
            }
        }
    }
```

Trying to get the lexeme on line three throws an exception:
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 4

	at java.lang.String.<init>(String.java:205)
	at org.fife.ui.rsyntaxtextarea.TokenImpl.getLexeme(TokenImpl.java:446)
        at cssTokenizerTest(RstaTokenizerTest.java:105)
...
```

Let me know if you need any additional information , thanks

**Comment by DexterHaslem** [comment]
Actually, to simplify it a bit, its not related to multi-line. heres a better example:

```java
        String line = "/**";
        Segment segment = new Segment(line.toCharArray(), 0, line.length());
        Token token = cssTokenMaker.getTokenList(segment, TokenTypes.NULL, 0);
        while (token != null)
        {
            System.out.println(token.getLexeme());
            token = token.getNextToken();
        }
```

The exception occurs on trying to get the Lexeme of the second, NULL token entry. But it works on other inputs with the usual '<null token>' representation.

**Comment by bobbylight** [comment]
In the library we should be looping through tokens via:

```java
while (token != null && token.isPaintable()) {
   ...
}
```

The token that fails on `toString()` for you is a special end-of-line that means "the next line starts in a multi-line comment".  Though I suppose, typing this out, your point is that toString() shouldn't throw an exception for this token?  If so that's totally a fair point.

**Comment by DexterHaslem** [comment]
I reckon, tho I only hit it on this lexer and not others, maybe by chance. Thanks, appreciate it
