### ISSUE TITLE
3.0.1 on mvnrepository.com official?

### ISSUE THREAD

**Issue by stolsvik** [bobbylight/RSyntaxTextArea#290]
Is this version released by this project?
https://mvnrepository.com/artifact/com.fifesoft/rsyntaxtextarea/3.0.1

The "Releases" page for this project does not list 3.0.1, and that page is different from previous releases (missing license and link to project page..)

**Comment by bobbylight** [comment]
It is, but somehow the release is incomplete. The jar itself is missing, as
well as the pom file.  Not sure what happened here.  I might try a
follow-up 3.0.2.

**Comment by stolsvik** [comment]
So that's the reason it was not listed here either? https://github.com/bobbylight/RSyntaxTextArea/releases
Seems like you should try to get rid of that 3.0.1 thing from Maven, then.

**Comment by bobbylight** [comment]
3.0.1 is borked, but 3.0.2 is out and is a valid release.  While I work to get 3.0.1. removed I'll go ahead and close this ticket.
