### ISSUE TITLE
Feature request: allow disabling link scanning mask

### ISSUE THREAD

**Issue by asashour** [bobbylight/RSyntaxTextArea#297]
Currently, `setLinkScanningMask()` requires some combination of key to enable link scanning, and it may not be very intuitive for the end users.

Disabling it (e.g. by allowing 0 as value), obviously has performance issue because it would trigger the `LinkGenerator` many times, but probably it can be an option for the developer.

**Comment by bobbylight** [comment]
It turns out you can disable the hyperlink scanning code via `setHyperlinksEnabled(false)`, rather than mucking with the mask key.  I've updated the JavaDoc for the class to be explain that since the latter method wasn't mentioned from the former, so it would be hard for folks to know that.

**Comment by asashour** [comment]
Thanks for replying, I guess I didn’t explain well.

What is suggested is having hyperlinks, but without the user need to click the special mask key, in other words, by just hovering with the mouse, the hyperlink is shown.

**Comment by bobbylight** [comment]
Oh OK.  In that case we already have #119 open to track this.  Sorry for the confusion.
