### ISSUE TITLE
License: is it "modified BSD" or just "BSD-3-Clause"?

### ISSUE THREAD

**Issue by vlsi** [bobbylight/RSyntaxTextArea#299]
RSyntaxTextArea license is declared as "modified BSD license", however:
1) It looks pretty much like https://spdx.org/licenses/BSD-3-Clause.html
2) The license link at http://bobbylight.github.io/RSyntaxTextArea/ page does not work (it produces 404)

Could you please clarify if https://github.com/bobbylight/RSyntaxTextArea/blob/d3722e5805c086b758e2e5c03d796304a7589d73/RSyntaxTextArea/src/main/dist/RSyntaxTextArea.License.txt is up to date?
Could you please clarify how the file differs from BSD-3-Clause?

As far as I can compare the above RSyntaxTextArea.License.txt with "SPDX version of BSD-3-Clause" I fail to find differences.

**Comment by vlsi** [comment]
PS. It would be great if you could include LICESE file to the root of the project so everybody (including GitHub UI) can see the license

**Comment by vlsi** [comment]
PS. Thanks for the project. I discovered this issue while analyzing licensing for third-party software used by Apache JMeter

**Comment by bobbylight** [comment]
I used the terminology "modified BSD license" for the reasons described here:

https://en.wikipedia.org/wiki/BSD_licenses#Previous_license

That was a long time ago, but I wanted a liberal license to facilitate the library's adoption and it seemed that the modified/3-clause was the way to go.  From your comments I gather the 3-clause version is pretty standard now, and the term "modified" is confusing?

**Comment by vlsi** [comment]
SDPX is a standard way of assigning license ids: https://spdx.org/licenses/

The below summarizes https://github.com/bobbylight/RSyntaxTextArea/issues/299 and https://github.com/bobbylight/RSyntaxTextArea/issues/300

So
1) Please add `Bundle-License: BSD-3-Clause` manifest entry (where `BSD-3-Clause` is SPDX identifier, see https://osgi.org/specification/osgi.core/7.0.0/framework.module.html#framework.module-bundle-license )
Adding explicit `Bundle-License` would simplify automatic analysis.

2) Please add LICENSE files to the produced jar files as `META-INF/LICENSE` file.
The thing is the license requires re-distributions to reproduce copyright notice, however it is really hard to do that in an automatic way, taking into account `rsyntaxtextarea.jar` is often taken from Maven Central. The jar file just misses NOTICE file, so it is really hard to reproduce copyright notice and track it for all rsyntaxtextarea upgrades.

3) You might want to use BSD-3-Clause in the pom file as well. Current license name in the pom.xml is "Modified BSD License". Using <licence><name>BSD-3-Clause</name> would help even humans to recognize the license and comply with it better.

**Comment by bobbylight** [comment]
Hopefulliy this is all wrapped up in the master branch and will be in the next release.
