### ISSUE TITLE
Add support for HyperLink leave events

### ISSUE THREAD

**Issue by siggemannen** [bobbylight/RSyntaxTextArea#301]
First and foremost, I want to thank the developer for an awesome component! It's so well done and thought out.

I have one small request. LinkGenerator is working fine, but i'm also showing a small popup with some extra choices when hovering over the link, that i want to close when user "leaves" the hyperlink, or releases Ctrl key.

But I don't see an easy way to do it right now, even extending textarea doesn't work, because of non-visible state fields.

It would be nice if RSyntaxTextArea could raise an event in case of leaving the hyperlink, for example through the HyperLinkListeners registered to it.

**Comment by bobbylight** [comment]
Done!  Hyperlinks will now fire entered- and exited-events, assuming the link scanning mask's modifier key is depressed.

**Comment by todaviaCaliente** [comment]
I have some doubts about the solution.

Class which implements LinkGeneratorResult is not informed about event type.
Previously 'execute' method was triggered only for EventType.ACTIVATED.
With implemented solution it's also triggered also for EventType.ENTERED.
Now it's not possible to distinguish these two cases inside LinkGenerator/LinkGeneratorResult.
Or am I missing smth?
