### ISSUE TITLE
Error UIManager does not support color key 'Label.disabledForeground'

### ISSUE THREAD

**Issue by jmetertea** [bobbylight/RSyntaxTextArea#304]
I use windows 7 and install latest JMeter 5.1.1 which uses rsyntaxtextarea-3.0.2.jar
On JMeter startup I get 2 same errors in log relevant to RSyntaxTextArea library:

> ERROR e.l.j.w.GuiUtils: UIManager does not support color key 'Label.disabledForeground'

Is it a bug or how can this be fixed/avoided?

**Comment by bobbylight** [comment]
This doesn't appear to be related to RSTA.  GuiUtils is not a class in this library.  Can you provide the full stack trace?

**Comment by bobbylight** [comment]
This doesn't seem to be an RSTA issue, and has been dormant for 6 months, so I'm closing.
