### ISSUE TITLE
copyAsStyledText() --> Paste to simple text editor removes new lines

### ISSUE THREAD

**Issue by gerdwagner** [bobbylight/RSyntaxTextArea#307]
In SQuirreL SQL, which embeds RSyntax, a call to RSyntaxTextArea.copyAsStyledText() leads to a loss of new lines when the copied text is pasted to a simple text editor. 

I suppose in RtfToText.endControlWord() the line 
if ("par".equals(word))
should be replaced by
if ("par".equals(word) || "line".equals(word))

For reference see
https://sourceforge.net/p/squirrel-sql/bugs/1394/

**Comment by bobbylight** [comment]
Fixed at master; I'll publish a SNAPSHOT build with this fix to Sonatype when I'm at my main machine.  A real 3.0.4 release shouldn't be too far in the future as well.
