### ISSUE TITLE
Line ending characters not handled property on Windows

### ISSUE THREAD

**Issue by marnee01** [bobbylight/RSyntaxTextArea#308]
I am using version 3.0.3. (Thank you for this library! It's a huge boon for us.)

There is a problem with how the editor handles line endings on Windows (which uses carriage-return/line-feed chars at end of line.) It seems the editor treats the carriage-return and line-feed characters as individual characters.

I've created a little Main class with main method you can use along with the specified steps to reproduce this issue.

The following are test cases, with expected and observed behavior. To start each test case, run (or rerun) the main method in the attached class on Windows. (Rename the attached file [Main.txt](https://github.com/bobbylight/RSyntaxTextArea/files/3487918/Main.txt) as Main.java first.)

===========Case 1 - Arrow Key=================

1. Run the main method.
2. Click the cursor on the end of the first line (just to the right of "Property1=true").
3. Hit left arrow key once.

Expected: Cursor is now between the 'u' and the 'e' in "true".
Observed: The cursor does not appear to move. It is still positioned at the end of the line. (And what is happening is that it is now between the Carriage-return and the Line-feed characters.)

===========Case 2 - Arrow Key Plus Enter Key=================

The following is a side-effect of the defect above:
1. Run the main method.
2. Click the cursor on the end of the first line (just to the right of "Property1=true").
3. Hit left arrow key once.
4. Hit enter
5. Click Save To Temp File

Expected for UI: Because the cursor was still showing at the end of the line, the expectation is that a "blank line" is added after the first line.
Observed for UI: As expected, the UI displays a blank line after the first line. However, behind the scenes there is a problem, as explained below.

Expected for underlying string: When we examine the actual text of the textarea (by writing to file and then examining the file), we expect that the following was written, where "\r" is carriage-return char and "\n" is the line-feed char:
Property1=true\r\n
\r\n
Property2=false

Observed for underlying string: Open the file that was written. The console will tell you the path of the file. Display in something like Notepad++ and display line wrap characters. (In Notepad++, click View-> Show Symbol -> Show End of Line.) 
Property1=true\n
\r\n
Property2=false
Notice there is no \r before the \n on the first line. This eventually causes problems for us.

You may wonder why a user would do this. A user could very well do this. If they hit left arrow and went to then hit enter, they may do it so quickly, they don't notice that the cursor has not appeared to move.

==========Case 3 - Delete Key=================
1. Run the main method.
2. Click the cursor on the end of the first line (just to the right of "Property1=true").
3. Click Delete key once.
5. Click Save To Temp File

Expected for UI: As in any text editor, we would expect that the line separator chars will be deleted and thus the second line is now appended to the first. So, the UI should show a single line: "Property1=trueProperty2=false".
Observed for UI: As expected. However, behind the scenes there is a problem, as explained below.

Expected for underlying string: When we examine the actual text of the textarea (by writing to file and then examining the file), we expect that the following was written (as single line):
Property1=trueProperty2=false

Observed for underlying string: Open the file that was written. The console will tell you the path of the file. Display in something like Notepad++ and display line wrap characters. (In Notepad++, click View-> Show Symbol -> Show End of Line.) 
Property1=true\r
Property2=false
Notice there is a \r at the end of line one. What is happening is that when user clicks Delete, it deletes the line-feed char (\n), but not the carriage-return char (\r).

==========Case 4 - Backspace Key=================

1. Run the main method.
2. Position the cursor on the beginning of the second line (just to the left of "Property2=false").
3. Click Backspace key once.
5. Click Save To Temp File

Results are same as previous test case for Delete key.

**Comment by bobbylight** [comment]
Swing text components always use \n for line terminators internally.  This means if you set content via `setText()` like you're doing, you need to use \n regardless of the OS.

If you're reading from a file or classpath resource, it's easiest to use the `JTextComponent.read(Reader, Object` method, since it handles normalizing newlines to \n.

Another alternative is a subclass of `RSyntaxTextArea`, `org.fife.ui.rsyntaxtextarea.TextEditorPane`, and use its `load(FileLocation, String)` method.

**Comment by marnee01** [comment]
Ah, that explains it. I have rarely worked with Swing in the past 8 years or so, so I had forgotten that. And thank you for the tips!
