### ISSUE TITLE
Question: How to load RTF file and display it in Rich Text?

### ISSUE THREAD

**Issue by neon1300** [bobbylight/RSyntaxTextArea#309]
I am a newbie in java programming, and I am trying to create an open function that loads RTF files and displays them in RSyntaxTextArea. 
I have tried varies methods such as RTFeditorKit, and have no luck.
Can someone please kindly enlighten me? 
Thank you.

**Comment by bobbylight** [comment]
Closing due to no response.  Please reopen if you are interested in a TokenMaker to style the RTF document format.  If you're looking to display RTF documents take a look at RTFEditorKit in the standard JDK.
