### ISSUE TITLE
how to implement

### ISSUE THREAD

**Issue by iamabs2001** [bobbylight/RSyntaxTextArea#315]
hi im trying to impplement this library from last week but i failed. where and how to put libraries and how to import them its very hard to do that plz help

**Comment by bobbylight** [comment]
RSTA can be used like any other Java library. Just add the jar to the classpath of your application when running it. For example, the simplest approach is:

```java
java -cp rsyntaxtextarea-3 0.4.jar MyApp.class
```

**Comment by iamabs2001** [comment]
Thanks first i seen so many java files its war not packed in jar so i
consufed what to do now i make an awesome ide with that :)
