### ISSUE TITLE
Edit Menu support

### ISSUE THREAD

**Issue by brunchboy** [bobbylight/RSyntaxTextArea#316]
As I mentioned in the RSTAUI project, I am finding RSyntaxTextArea fantastically useful in helping users of my [Beat Link Trigger](https://github.com/Deep-Symmetry/beat-link-trigger#beat-link-trigger) project edit snippets of Clojure code to build their own integrations with light, laser, video, and music equipment. I very much appreciate the functionality that is available in the context (popup) menu, but I would like to make that more discoverable by mirroring it in an Edit menu in my own menu bar.

At the moment the only way I can think of to do that is to re-implement all the logic myself, and try to monitor the RSyntaxtTextArea to figure out when I need to enable and disable menu items.

It would be lovely if you could provide a `getEditMenu` method that would simply return such a menu that I could add to my menu bar, whose contents are menu items based on the same actions used in your popup menu, so they automatically enable and disable in parallel with the popup menu items.

Might that be feasible?

**Comment by siggemannen** [comment]
You can do something like:
Action a = RTextArea.getAction(RTextArea.PASTE_ACTION);

this would fetch the binded action for the Paste. You can then set them on your menu, and i think they should be updated correctly.

**Comment by brunchboy** [comment]
Oh, thanks, I will give that a try!

**Comment by brunchboy** [comment]
Thanks, this does indeed work great! I was able to create an Edit menu with all the items from the popup menu, with the following Clojure code:

```clojure
(seesaw/menu :text "Edit"
             :items [(RTextArea/getAction RTextArea/UNDO_ACTION)
                     (RTextArea/getAction RTextArea/REDO_ACTION)
                     (RTextArea/getAction RTextArea/CUT_ACTION)
                     (RTextArea/getAction RTextArea/COPY_ACTION)
                     (RTextArea/getAction RTextArea/PASTE_ACTION)
                     (RTextArea/getAction RTextArea/DELETE_ACTION)
                     (RTextArea/getAction RTextArea/SELECT_ALL_ACTION)])
```

I was delighted to find this also displayed the keyboard shortcuts (which the popup menu does not), so it will make it even easier for my users to discover these conveniences.

You might want to add a suggestion about how to do this to the overview documentation and/or tutorial, but if that seems unnecessary to you, then please feel free to close this issue.

Thanks again for your help.

**Comment by bobbylight** [comment]
Haha I'm glad someone chimed in since I'm so late to respond these days.  :)  Yes, I had a similar requirement for the editor I use RSTA in, hence this API.

I'll keep this open to consider adding an item about it to the wiki.

**Comment by bobbylight** [comment]
I've added a wiki entry:  [Adding an Edit menu for the editor](https://github.com/bobbylight/RSyntaxTextArea/wiki/Example:-Adding-an-Edit-menu-for-the-editor).
