### ISSUE TITLE
Backgroundcolor of Token paints over Syntax Highlighting

### ISSUE THREAD

**Issue by giraphiki** [bobbylight/RSyntaxTextArea#317]
After migrating from RSTA 1.5.2 to Version 3.0.2 I noticed that the highlighting for spelling errors is no longer visible. At least as long as the words are not selected/marked.
After some testing I narrowed the problem down to the background color of the Tokens. I have the background color of Tokens from the type `IDENTIFIER` set to white. Only when the Color is set to null the squiggly underline is visible.

I prepared an example to show the problem:

![RSyntaxTextArea-Test-Background=null](https://user-images.githubusercontent.com/37336648/68865793-af888200-06f3-11ea-93d7-b4bdcb2ca060.png)
Token backgroundcolor set to the default which is null.

![RSyntaxTextArea-Test-Background=green](https://user-images.githubusercontent.com/37336648/68865817-badbad80-06f3-11ea-87f6-cfae0e7a8f63.png)
Token background color set to Color.GREEN.

![RSyntaxTextArea-Test-Selection](https://user-images.githubusercontent.com/37336648/68865825-bfa06180-06f3-11ea-8c7c-e093b8a67e2f.png)
Selection of some words shows the spelling errors.

If I analysed it correctly this happens because the Tokens are drawn on top of the spelling error highlights. It seems as if it happens in the `DefaultTokenPainter` in the `paintImpl` method.

**Comment by bobbylight** [comment]
Good catch, thanks.  I think we can address this by simply deferring the rendering of parser highlights (which are typically squiggle-underlines) until after the text is rendered, as you suggest.  Other highlights will still be rendered before/underneath the text.

**Comment by bobbylight** [comment]
Also note I've been tweaking SpellChecker to be a little smarter too with things words that are camelCased, and filled in a few spelling gaps I noticed (typically programming-related words), but if you know of any valid words that are flagged such as "canine" let me know and I can add 'em to the default dictionary.

**Comment by PAX523** [comment]
> 
> 
> Also note I've been tweaking SpellChecker to be a little smarter too with things words that are camelCased, and filled in a few spelling gaps I noticed (typically programming-related words), but if you know of any valid words that are flagged such as "canine" let me know and I can add 'em to the default dictionary.

Thanks, but that's no problem for us. We are using a separate spell checking implementation in our integration of `RSyntaxTextArea`.

**Comment by bobbylight** [comment]
Until I get a release out, you can try out the fix by building from source or pulling the SNAPSHOT from https://oss.sonatype.org/content/repositories/snapshots.
