### ISSUE TITLE
Receiving notifications about modifications ?

### ISSUE THREAD

**Issue by Alex-www** [bobbylight/RSyntaxTextArea#318]
Is there an orderly way of receiving notifications about modifications to the text area short of implementing a key listener and checking the undo stack ?

Need to set status information like a dirty-marker etc.

TIA - Alex

**Comment by bobbylight** [comment]
Aye, RSTA is a standard `JTextComponent` so you can use a `DocumentListener`: 
 https://docs.oracle.com/javase/tutorial/uiswing/events/documentlistener.html
