### ISSUE TITLE
JSON: arrays are not collapsible

### ISSUE THREAD

**Issue by smileatom** [bobbylight/RSyntaxTextArea#321]
Hi,

Although objects are collapsible in the editor, Arrays [...] are not.  Is there an option or config for this?

Thanks

**Comment by bobbylight** [comment]
This is working for me, try the `RSyntaxTextAreaDemoApp` submodule for exmaple.  Can you provide an [SSCCE](http://sscce.org/) that demonstrates the problem?

**Comment by smileatom** [comment]
Ill get back to you on this tommorow.

**Comment by smileatom** [comment]
Your right I was incorrect.
