### ISSUE TITLE
COMMENT_KEYWORD and COMMENT_MARKUP tokens not painting properly

### ISSUE THREAD

**Issue by shinobisoft** [bobbylight/RSyntaxTextArea#324]
Token.COMMENT_KEYWORD and Token.COMMENT_MARKUP are NOT being rendered as set either by API or XML theme. Token.COMMENT_DOCUMENTATION, Token.COMMENT_EOL and Token.COMMENT_MULTILINE are being rendered correctly.

Is it possible that Token.COMMENT_KEYWORD and Token.COMMENT_MARKUP are being painted first, then painted over by Token.COMMENT_DOCUMENTATION, Token.EOL or Token.MULTILINE?

I have 2 versions of RSyntaxTextArea, 2.5.8 and 3.0.3. This persists in both versions.

EDIT:
I just built RSyntaxTextArea 3.0.5 SNAPSHOT. This issue persists there too.

**Comment by bobbylight** [comment]
Both of these token styles are used in JavaTokenMaker to render "special" tokens in Javadoc.  Can you provide an [SSCCE](http://sscce.org/), or point to a repo with source that reproduces the problem?

**Comment by shinobisoft** [comment]
Well... I wasn't aware of that, unfortunately. This would be a nice enhancement for languages, like C++, that share multi-line and documentation comment styles... Just a thought!

**Comment by bobbylight** [comment]
Oh I see - you're just saying that those token styles aren't used in C++ (for example), when they could/should be?

Yes, it's a design flaw in RSTA that the parsing/token rendering code cannot be shared between different `TokenMaker` implementations, nor can one delegate to another.  Each language's `TokenMaker` must be written to take advantage of token styles and other features, even if it means duplicating code across lexers.  In practice this duplication isn't so bad really, except for web languages where there's so much overlap (e.g. HTML, PHP, JSP, and Vue lexers all share a lot of code in common with one another, in addition to the plain old JS lexer which is essentially copy-pasted into each of them).

Feel free to open a feature request for enhancements to the C++ lexer, or any others, that you'd find useful.  That kind of thing is usually easy to add, but I usually don't go back and update lexers for file types I don't use without being poked about it :)

**Comment by shinobisoft** [comment]
Correct!!! LOL! Great, I'll submit a feature request soon. Thanks!!!
