### ISSUE TITLE
Clearing undo/redo actions

### ISSUE THREAD

**Issue by shinobisoft** [bobbylight/RSyntaxTextArea#325]
This is a feature request.

Public access to RUndoManager or methods that access RUndoManager so that we can clear undo/redo buffers. RSyntaxTextArea.undoLastAction() will currently delete the textual content of a control because RSyntaxArea.setText() does NOT clear the undo/redo buffers as I think it should. Unless I'm missing something...

**Comment by bobbylight** [comment]
If all you need to do is clear the undo stack, you should be able to call `discardAllEdits()`.

**Comment by shinobisoft** [comment]
Thank you for the reply. I had actually just found the `discardAllEdits()` method. This will work for me. Thank you!
