### ISSUE TITLE
Token.getTokenList loses some context info

### ISSUE THREAD

**Issue by siggemannen** [bobbylight/RSyntaxTextArea#330]
Hi!

I've hit a bit of a snag when working on nested multiline-comments in TSQL language, they're in form of:
```
  /*nested comment
         /*another nested 
           comment*/ Inner text
   */
```
The result of this is that whole thing should be a big long multiline-comment.
It works fine when parsing whole document (I use a custom parser and not the build in sql one), the problem is when it comes to painting some specific lines in the RSyntaxTextArea.

The problem is:

When getting tokens for the line of "comment*/ Inner text" , the initialTokenType from previous line doesn't really say that it's itself a nested comment, therefor the "Inner text"-part becomes uncommented.

I was thinking of "encoding" the nest level inside the previous token type by setting it to some large number + nest level, but then the problem is that i want to get the "original" token type back when painting it in the RTextArea, and it quickly gets pretty messy.

Any suggestions?

**Comment by bobbylight** [comment]
Yeah it gets messy. Writing TokenMakers is a little bit of a sore spot in the library :)

There are some languages that RSTA supports today that allow for nested comments.  One that is probably one of the simplest is [DTokenMaker.flex](https://github.com/bobbylight/RSyntaxTextArea/blob/master/RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/modes/DTokenMaker.flex).  It does exactly what you say - encodes the comment level as part of the end-of-line token value - and it does indeed get messy.  However, all built-in TokenMakers that support nested commentes follow this paradigm.

If the only token type that allows nesting is comments, it's not too bad.  The gist is to reserve a few bits in the end-of-line token type to denote the amount of nesting.  This does of course mean there's an upper bound after which RSTA won't properly render files, but you can make that bound sufficiently large for any real-world file.

Starting points in `DTokenMaker.flex` include:

* The token type, [INTERNAL_IN_NESTABLE_MLC](https://github.com/bobbylight/RSyntaxTextArea/blob/master/RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/modes/DTokenMaker.flex#L72)
* [addNestedMlcEndToken()](https://github.com/bobbylight/RSyntaxTextArea/blob/master/RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/modes/DTokenMaker.flex#L99) method
* The [default state in the getTokenList()](https://github.com/bobbylight/RSyntaxTextArea/blob/master/RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/modes/DTokenMaker.flex#L212) method, which extracts the nested MLC depth when starting to paint a line that is in a (possibly) nested multi-line comment.
* The [NESTABLE_MLC](https://github.com/bobbylight/RSyntaxTextArea/blob/master/RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/modes/DTokenMaker.flex#L605) state itself, which increments/decrements the MLC depth counter whenever a start/end token for a MLC is seen.
* The [getClosestStandardTokenTypeForInternalType()](https://github.com/bobbylight/RSyntaxTextArea/blob/master/RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/modes/DTokenMaker.flex#L158) method, which needs to be implemented in cases like yours.

If you follow this paradigm you should be fine.  Let me know if you have any questions!

**Comment by siggemannen** [comment]
Hi again. I have solved the nested comments with help of your pointers, and the comments are painted beatifully, thanks a bunch!
I missed the "addNestedMlcEndToken()" part, where you insert an end token with magic negative value that isn't used for rendering, but it's available when parsing next line!

**Comment by bobbylight** [comment]
No problem, glad you're up and running!
