### ISSUE TITLE
Syntax highlighter does not recognize python keywords

### ISSUE THREAD

**Issue by olegvasylenko** [bobbylight/RSyntaxTextArea#338]
Syntax highlighter does not recognize python keywords: **None**, **True**,  **False**

rsyntaxtextarea: V3.1.0
syntax: SyntaxConstants.SYNTAX_STYLE_PYTHON

See: https://docs.python.org/3/reference/lexical_analysis.html#keywords

**Comment by bobbylight** [comment]
Thanks!
