### ISSUE TITLE
Fix #301 vs LinkGenerator

### ISSUE THREAD

**Issue by todaviaCaliente** [bobbylight/RSyntaxTextArea#340]
I have some doubts about the solution:
https://github.com/bobbylight/RSyntaxTextArea/commit/9bc9f187b84e3fad5000970267360bf843d422bb

Class which implements LinkGeneratorResult is not informed about event type.
Previously 'execute' method was triggered only for EventType.ACTIVATED.
With implemented solution it's also triggered for EventType.ENTERED.
Now it's not possible to distinguish these two cases inside LinkGenerator/LinkGeneratorResult.
Am I missing smth?

**Comment by bobbylight** [comment]
This is a dupliate of #390.  Dup'ing this one to that one only because it's newer.  Somehow this got overlooked previously, apologies!
