### ISSUE TITLE
RSyntaxTextArea isn't automatically resizable

### ISSUE THREAD

**Issue by recursivetree** [bobbylight/RSyntaxTextArea#342]
I want to create a window with a RSyntaxTextArea in it. If I resize the window, the textarea should resize, but if I instruct the Layoutmanager to do so, it doesn't work

**Comment by bobbylight** [comment]
If this is reproducible, please reopen and post an SSCCE demonstrating the problem.  RSTA should resize with a proper LayoutManager, e.g. BorderLayout.  See the example in this project's[ README.txt ](https://github.com/bobbylight/RSyntaxTextArea/blob/master/README.md) (or the RSyntaxTextAreaDemo submodule in this project) for an example.
