### ISSUE TITLE
Auxiliary Project - File Manager

### ISSUE THREAD

**Issue by ricardojlrufino** [bobbylight/RSyntaxTextArea#348]
Hi, how are you ?
I was one of those responsible for putting RSyntaxTextArea in the Arduino IDE. I would like to thank you for the project.

looking for a component to manage files, I didn't find any project that could help. I ended up creating a component for this purpose, I believe that it can eventually be useful for for users using RSyntaxTextArea.

I am grateful if you have any feedback to give:
https://github.com/ricardojlrufino/JExplorerTree

**Comment by bobbylight** [comment]
Always good to see new Swing development :)

**Comment by ricardojlrufino** [comment]
it seems that nobody else uses it right?
