### ISSUE TITLE
difference in behavior of TAB when only line and multiple lines selected

### ISSUE THREAD

**Issue by raydac** [bobbylight/RSyntaxTextArea#354]
If I select multiple lines and hit 'Tab', all these lines will be indented, it's fine, but if select only one line and hit 'Tab', this line will be replaced by a 'tab' character , I think the behavior should be the same with previous.

**Comment by bobbylight** [comment]
Sounds good, thanks for the suggestion. It does seem like code editors do this these days.  I'll add it in.
