### ISSUE TITLE
Keyboard shortcuts don't in MacOS with Nimbus

### ISSUE THREAD

**Issue by albinowax** [bobbylight/RSyntaxTextArea#356]
It appears that keyboard shortcuts like ctrl+a and cmd+a don't in MacOS inside an RSyntaxTextArea with the Nimbus look and feel. Changing the look and feel avoids this issue.

**Comment by bobbylight** [comment]
Cmd+A, Cmd+C and Cmd+V seem to all work for me in Nimbus on OS X.  Can you provide a simple test case that demonstrates this problem?  Note most shortcuts are Cmd+<something>, rather than Ctl+<something> on OS X (just mentioning it since you provided both Ctrl and Cmd as examples that didn't work).

**Comment by albinowax** [comment]
Ah sorry, that suggests this is probably due to an interaction between RSyntaxTextArea and the Burp Suite environment I'm using it in.

**Comment by bobbylight** [comment]
No worries. If you can come up with a test case outside of Burp feel free to reopen this!
