### ISSUE TITLE
Adding a new window/instance with the same 'settings'

### ISSUE THREAD

**Issue by kvnandula04** [bobbylight/RSyntaxTextArea#358]
Hi,

I am working on an IDE for my own language and I was wondering if there was a way to replicate multiple windows with the same properties? So I already have a window with a JMenu, items and a lot of properties. I want another window with the exact same methods and properties. 

My IDE looks like this:
![image](https://user-images.githubusercontent.com/34941351/96246056-02238b80-0fa0-11eb-832f-06ceb490c044.png)

And my code exists in this gist:
https://gist.github.com/kvnandula04/6159b95a146102ce0ce9d9f0b2fc1207

At the moment, my new file functionality is simply to check that the user has saved their current working file and then if saved, I just make the textarea empty again for working on the new project. Of course, this is not what users would expect. They'd want to work on multiple projects simultaneously. So, that's what I would like to implement.

Any help would be greatly appreciated. If you have any questions, please let me know.

**Comment by bobbylight** [comment]
If you're referring to the styling of the `RSyntaxTextArea` instance, you can use a `Theme` to define the style RSTA uses and apply that to every RSyntaxTextArea instance you create.  For more information, see [Example: Setting the theme](https://github.com/bobbylight/RSyntaxTextArea/wiki/Example:-Setting-the-theme).

If you're referring to two JFrames with the same menu items, all you have to do is create a reusable class or method that creates a `JMenuBar` a certain way, and call that to create/add your menu bar to every `JFrame` you create.

Does that help?

**Comment by kvnandula04** [comment]
Yeah, I'm referring to the 2 frames with the same menu items and functionality. If you look at [the code](https://gist.github.com/kvnandula04/6159b95a146102ce0ce9d9f0b2fc1207), you'll understand that I have an IDE that interprets my own language based on the text in the textArea. I want all of that code to work for the second window as well. Do you have any code samples for how to do what you suggested?

**Comment by kvnandula04** [comment]
Ok, so I worked out a way to do it. I simply just added a `newFile` method with the following code snippet:

`new IDE().setVisible(true);`

**Comment by omegaui** [comment]
Whoa! Great. 
I have also created an IDE using rsyntaxtextarea as the IDE's editor.
It is full of features. See if you can get some help!
Last stable version : https://github.com/omegaui/omegaide
Current beta version (cross platform) : https://github.com/omegaui/omegaide-dailybuilds
