### ISSUE TITLE
How to increase the line numbers font-size?

### ISSUE THREAD

**Issue by acwolff** [bobbylight/RSyntaxTextArea#363]
Being old, I have trouble reading small letters, so I make the font size of the editor quite large, which helps. But the letter size of the line numbers doesn't get bigger when I change the font size, can you change that please or tell me how to make the line numbers bigger?

**Comment by bobbylight** [comment]
The line number component is hidden (for some reason), but properties for it are accessible off of the `Gutter` component in an `RTextScrollPane`.  You can set the line number font programmatically via [setLineNumberFont()](https://github.com/bobbylight/RSyntaxTextArea/blob/master/RSyntaxTextArea/src/main/java/org/fife/ui/rtextarea/Gutter.java#L744) as follows:

```java
RTextScrollPane scrollPane = new RTextScrollPane(textArea, true);
scrollPane.getGutter().setLineNumberFont(new Font("Monaco", FontPLAIN, 24));
```
If you're using themes (see [Theme.java](https://github.com/bobbylight/RSyntaxTextArea/blob/master/RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/Theme.java)), you can define it there via `<lineNumbers fontSize="24"/>`.  Though none of the built-in themes override this property.
