### ISSUE TITLE
Long load in production, short under Eclipse 

### ISSUE THREAD

**Issue by idiatech** [bobbylight/RSyntaxTextArea#373]
Hello,

Thank you for this library, I have a somewhat strange problem, when I do Ctrl + Space in the editor the same tooltip loads immediately under Eclipse and 10 seconds when it is a .jar.
I tried 2 methods of loading my XML file but I think it has nothing to do with it because it doesn't change anything. I have more of the impression that it's the way your tool manages the cache that has an influence.

What am I doing wrong? How to speed up this loading? 

Thank you

```
synchronized private DefaultCompletionProvider createCodeCompletionProvider() {

		// Add completions for the C standard library.
		DefaultCompletionProvider cp = new DefaultCompletionProvider();

		// First try loading resource (running from demo jar), then try
		// accessing file (debugging in Eclipse).
		ClassLoader cl = getClass().getClassLoader();
		//String cheminTravail=Fc.ajouterSeparateur(Fc.ajouterSeparateur(System.getProperty("user.home"))+"Folder");
		try {
			InputStream in = cl.getResourceAsStream("myFile.xml"); //new FileInputStream(cheminTravail+"myFile.xml"); 
			if (in!=null && in.available()>0) {
				try {
					cp.loadFromXML(in);
				} catch(Exception e) {
					e.printStackTrace();
				}
				in.close();
			}
			else {
				cp.loadFromXML(new File("grimport.xml"));
			}
		} catch (IOException ioe) {
			ioe.printStackTrace();
		}
		
		Iterator<String> it=variablesDansLediteur.iterator();
		while(it.hasNext())
		{
			String variable=it.next();
			BasicCompletion completion=new BasicCompletion(cp, variable);
			completionsDeVariables.add(completion);
			
			cp.addCompletion(completion);
		}
}

synchronized CompletionProvider createCompletionProvider() {

	    // A DefaultCompletionProvider is the simplest concrete implementation
	    // of CompletionProvider. This provider has no understanding of
	    // language semantics. It simply checks the text entered up to the
	    // caret position for a match against known completions. This is all
	    // that is needed in the majority of cases.
				// fonctions grimport
				if(codeCP==null) codeCP = createCodeCompletionProvider();
				else codeCP = completerVariables(codeCP);

				// The provider used when typing a string.
				if(stringCP==null) stringCP = createStringCompletionProvider();

				// The provider used when typing a comment.
				if(commentCP==null) commentCP = createCommentCompletionProvider();

				// Create the "parent" completion provider.
				LanguageAwareCompletionProvider provider = new LanguageAwareCompletionProvider(codeCP);
				provider.setStringCompletionProvider(stringCP);
				provider.setCommentCompletionProvider(commentCP);

	  

	    return provider;

	 }

```

**Comment by bobbylight** [comment]
A few questions:

* When you say "the tooltip" takes 10 seconds, do you mean the list of completion choices?
* Is it a 10-second wait every time you press Ctrl+Space, or just the first time?  If it's just time, it could be a performance issue with loading
* What specific code path is it taking when you see the issue?  e.g. is it the call to `cp.loadFromXML()` taking the `InputStream` parameter or the one taking the `File` parameter?  And when it's fast, is it taking the other code path?  This will narrow down where the problem is.

**Comment by idiatech** [comment]
Hello,

First of all, thank you for agreeing to answer me. Here is my answer :
1) Yes it is about the choice of completions
2) The 10 seconds should be waited every time, not just the first time.
3) I did performance tests and in fact the problem does not come from my 
lines of code, the 10 seconds are between the moment I press Ctrl + 
Space and the display of the completion box. But the XML was loaded long 
before, so it doesn't matter.
Under Eclipse it's immediate and when I produce the jar it takes 10 
seconds, I don't know what to tell you others.

Thank you

Xavier


	
	

Le 09/05/2021 à 00:32, bobbylight a écrit :

**Comment by bobbylight** [comment]
Not sure what the issue is, sorry.  My only advice is to attach a remote debugger or profiler to your production app and try to track down what the issue is.  I can't reproduce it in my own applications.  If you find a bug feel free to reopen this ticket or create a new one, but for now this sounds like some sort of configuration issue.
