### ISSUE TITLE
Support for Kotlin in parser

### ISSUE THREAD

**Issue by olonho** [bobbylight/RSyntaxTextArea#375]
Any chances that `SyntaxConstants.SYNTAX_STYLE_KOTLIN` will appear?
If implemented, could it get merged?

**Comment by bobbylight** [comment]
I'll take a first stab at this and make a SNAPSHOT jar, though I don't know Kotlin so I'd appreciate someone take a look at the SNAPSHOT and provide feedback.

Should it colorize some of the most common JDK classes (java.lang.*, java.io,*, java.util.*) like `JavaTokenMaker` does?

**Comment by olonho** [comment]
Amazing, we’ll take a look. Guess JDK classes shall be colorized.

**Comment by olonho** [comment]
How we could use the SNAPSHOT version? https://oss.sonatype.org/content/repositories/snapshots/com/fifesoft/rsyntaxtextarea/ seems to have somewhat older version. We use Gradle, so proper `implementation` would be cool, currently we use 
`implementation(group = "com.fifesoft", name = "rsyntaxtextarea", version = "3.1.2")`

**Comment by bobbylight** [comment]
Yeah it's not out there yet.  Got too sleep yesterday to finish it :)

**Comment by bobbylight** [comment]
OK, the latest 3.1.3-SNAPSHOT on Sonatype should include support for `SYNTAX_STYLE_KOTLIN`, both syntax highlighting and code folding.  Try it out and reply back with what's missing or not working right!

**Comment by bobbylight** [comment]
@olonho , have you had a chance to check out the Kotlin support in 3.1.3-SNAPSHOT yet?

**Comment by olonho** [comment]
Yep, simple Compose app like this one with `3.1.3`: 

```kotlin
import androidx.compose.desktop.SwingPanel
import androidx.compose.desktop.Window
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.size
import androidx.compose.material.Button
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Text
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea
import org.fife.ui.rsyntaxtextarea.SyntaxConstants
import org.fife.ui.rtextarea.RTextScrollPane
import javax.swing.BoxLayout
import javax.swing.JPanel
fun main() = Window {
    MaterialTheme {
        val text = remember {
            mutableStateOf("Привет \uD83E\uDDD1\uD83C\uDFFF\u200D\uD83E\uDDB0\nالعاشر ليونيكود")
        }
        var textArea by remember { mutableStateOf<RSyntaxTextArea?>(null) }
        var counter by remember { mutableStateOf(0) }
        Column {
            SwingPanel(
                background = Color.White,
                modifier = Modifier.size(600.dp, 400.dp),
                factory = {
                    JPanel().apply {
                        setLayout(BoxLayout(this, BoxLayout.Y_AXIS))
                        val newTextArea = RSyntaxTextArea("""
                            fun main() = println("Hello")
                        """.trimIndent(),20, 60)
                        newTextArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_KOTLIN)
                        newTextArea.setCodeFoldingEnabled(true)
                        val sp = RTextScrollPane(newTextArea)
                        add(sp)
                        textArea = newTextArea
                    }
                }
            )
            Button(onClick = {
                textArea?.let {
                    counter++
                    it.text = it.text + "\nfun foo$counter(): Int = $counter"
                }
            }) {
                Text("More")
            }
        }
    }
}
```
renders 
![image](https://user-images.githubusercontent.com/2600522/122230373-46b24e80-cec2-11eb-9989-29ebf69c9852.png)

**Comment by bobbylight** [comment]
Thanks. In that case I'll close this ticket out. I'm sure the syntax highlighting is incomplete so feel free to open another ticket with any issues you find.
