### ISSUE TITLE
Unexpected background and foreground colors in RSTA tool tip

### ISSUE THREAD

**Issue by antimatter84** [bobbylight/RSyntaxTextArea#377]
Highlighted errors in RSTA show a message in a tool tip, when hovering with the mouse over the offending token.
Our Java application offers a dark theme and when used the background and text color of those tool tips are both white and hence unreadable. Also, the font color of the "Press F2 for focus" message seens too dark.

![grafik](https://user-images.githubusercontent.com/10585451/116402463-c316a280-a82c-11eb-9648-5d4746110112.png)

After debugging into the TipUtil class I found that a dark background color is retrieved from the UIManager but on the tip window, somehow white is used as background. 

How can I control those colors? The programmatical way is preferred.

**Comment by bobbylight** [comment]
Can you send me the LookAndFeel you're using?

**Comment by antimatter84** [comment]
I didn't get permission to send you the LookAndFeel and as it is the 4th derivative of Nimbus LAF, recreating it into a working example would be a lot of work. So I tested on openly available dark LookAndFeel (https://www.formdev.com/flatlaf/) and the tool tips look good with that one.

![grafik](https://user-images.githubusercontent.com/10585451/116566651-368ce280-a907-11eb-8326-fc8abb60d489.png)

I render simple plain text.

**Comment by bobbylight** [comment]
Either [TipUtil.getToolTipBackground()](https://github.com/bobbylight/RSyntaxTextArea/blob/master/RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/focusabletip/TipUtil.java#L98) is returning white (which I believe you said you've verified it isn't?), or the text being passed into the tool tip is HTML that e.g. sets the <body> tag's background to white (would be done at [TipWindow.java:87](https://github.com/bobbylight/RSyntaxTextArea/blob/master/RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/focusabletip/TipWindow.java#L87) if you want to debug to see what specifically is being passed).

I know you say you've already checked these things, but these are the only things I can think of.

Are you sure that:
* Your LookAndFeel doesn't extend Nimbus?
* `UIManager.getColor("ToolTip.background")` isn't white (or possibly `null`) in your LookAndFeel?

I'm trying to think of other explanations but those are the only possibilities I can think of at the moment.

**Comment by antimatter84** [comment]
I was able to fix the issue by providing a custom painter for JEditorPane to our LookAndFeel.
