### ISSUE TITLE
Propagation of Hyperlink event type outside source code seems impossible

### ISSUE THREAD

**Issue by Fir0x** [bobbylight/RSyntaxTextArea#390]
Hi,

It seems that it is impossible to propagate the events `HyperlinkEvent.EventType.ACTIVATED` and `HyperlinkEvent.EventType.ENTERED` outside the methods of the source code.
The `createHyperLinkEvent` method consumes the event type except if it is HyperlinkEvent.EventType.EXITED.
As the event type is not accessible from the `LinkGenerator` I don't see any way to distinct whether the user clicked on the link or just moved his mouse on it.

Is there a way I don't see or is this a source code issue?

**Comment by bobbylight** [comment]
Thanks, I'll take a look!

**Comment by bobbylight** [comment]
Looks like a refactor broke this at some point.  You're correct that the LinkGenerator's event triggers on mouse hover.  I'll troll through the repo history and figure out when this broke.

**Comment by bobbylight** [comment]
This should be fixed now and available on Sonatype as 3.1.4-SNAPSHOT.
