### ISSUE TITLE
Disabling occurrence marking when focus is lost

### ISSUE THREAD

**Issue by Sothatsit** [bobbylight/RSyntaxTextArea#391]
I have been trying to disable occurrence marking when the focus on a text area is lost.

My current approach has been to add a focus listener, and when the focus is lost use `setMarkOccurrences(false)`. This on its own however will not remove existing occurrences, so a `repaint()` has to be called as well after disabling mark occurrences.

This leads to issues however due to delays between when you move the caret over a token, to when the occurrences for that token are highlighted. Therefore, I run into the following issue:
1) Click on a token. _Occurrence marking for the token is started._
2) Press tab to move focus off of text area. _Mark occurrences is now disabled._
3) Occurrences for the token are found and painted, even though mark occurrences is disabled.

Therefore, I was wondering whether there is a better approach to disabling occurrence marking when the focus is not on the RSyntaxTextArea, or whether this could be fixed so that the occurrences that are found after occurrences are disabled can be ignored.

I think the underlying issue is that the _timer_ field in _MarkOccurrencesSupport_ does not get disabled after mark occurrences support is removed. I think this could be simply fixed by adding `timer.stop()` in the _MarkOccurrencesSupport.uninstall_ method.

Thanks!

**Comment by Sothatsit** [comment]
There is also another bug where the mark occurrences delay is not set when a new _MarkOccurrencesSupport_ is installed. Therefore, every time I enable mark occurrences I have to set it again. This wouldn't be so bad if RSyntaxTextArea didn't also check if the delay had changed. Therefore, I have to do the following just to set the delay to a constant 1 millisecond, while still retaining the ability to turn mark occurrences on and off:
```
setMarkOccurrences(true);
setMarkOccurrencesDelay(2);
setMarkOccurrencesDelay(1);
```

It would also be nice if we could set the delay to 0, but thats not a bug, just a feature that would be nice to have :)

**Comment by bobbylight** [comment]
Thanks for the bug report!  I think I've fixed all of the issues you mentioned.   Check it out in master or grab the latest `3.1.4-SNAPSHOT` from Sonatype.
