### ISSUE TITLE
Get token(text) below mouse

### ISSUE THREAD

**Issue by omegaui** [bobbylight/RSyntaxTextArea#393]
Hi!
Is there a way to get the **token or text (based on selected editing style)** below the mouse by using any HoverListener or something.
Like the editor identifies hyperlinks when mouse with CTRL mask down enters the url coordinates.

I want to implement in-editor **code navigation** feature in the IDE I am creating. See ![Omega IDE](https://github.com/omegaui/omegaide)

Waiting for your reply.

**Comment by bobbylight** [comment]
You should be able to use [RSyntaxTextArea.viewToToken(Point)](https://github.com/bobbylight/RSyntaxTextArea/blob/master/RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/RSyntaxTextArea.java#L3246) with the mouse position from say a `MouseListener` or `MouseMotionListener`.  Note however that this is a pretty expensive operation to tie to mouse motion so you might want to tie it to a slight delay, like tool tips do.

**Comment by omegaui** [comment]
Thanks! I will bind it with a key stroke.
