### ISSUE TITLE
Gradle task for RSyntaxTextAreaDemoApp?

### ISSUE THREAD

**Issue by dbenn** [bobbylight/RSyntaxTextArea#410]
I'm experimenting with `RSyntaxTextArea`. Thanks for a nice library and demo app.

I'm wondering whether it's worth having a `run` task in `build.gradle` to make it easier to run the `RSyntaxTextAreaDemoApp`, that runs the following:
~~~
java -cp RSyntaxTextAreaDemo/build/libs/rstademo-3.1.3.jar:RSyntaxTextArea/build/libs/rsyntaxtextarea-3.1.3.jar org.fife.ui.rsyntaxtextarea.demo.RSyntaxTextAreaDemoApp
~~~

**Comment by bobbylight** [comment]
Done!  Thanks!

**Comment by dbenn** [comment]
Thanks!
