### ISSUE TITLE
Java: Add new keywords

### ISSUE THREAD

**Issue by bobbylight** [bobbylight/RSyntaxTextArea#421]
Add syntax highlighting for contextual keywords added in more recent versions of Java.  Note these are all contextual, but it's probably save to just always highlight them as keywords since our lexers don't have semantic information, and it's probably rare to see these keywords used as say variable names anyway:

* sealed
* non-sealed
* var
* yield
* record

Other, module-specific keywords are less important since they aren't seen in code.

See: https://docs.oracle.com/javase/specs/jls/se17/html/jls-3.html#jls-3.9

**Comment by omegaui** [comment]
@bobbylight 

I have already done this, on my side around two months ago, if you haven't done this yet!
Then, I can open a pull request.

But you also need to add the Text Blocks part...

![Screenshot from 2021-12-31 10-12-57](https://user-images.githubusercontent.com/73544069/147803820-51153820-f0a8-451b-a844-76e88318a2c3.png)
