### ISSUE TITLE
Margin Line Color

### ISSUE THREAD

**Issue by ghost** [bobbylight/RSyntaxTextArea#43]
If i try to set the margin line color for a TextEditorPane like this

``` java
setMarginLineColor(new Color(248,248,248)); 
```

The color doesn't change.
I even changed the value in eclipse.xml theme file but that also doesn't work.

**Comment by salmanarif** [comment]
Hi! I'm trying to figure out how to use this for a project I'm currently working on.
At the moment, I am doing the following, but it seems to have no effect:

`codeScrollPane.setIconRowHeaderEnabled(true);
codeScrollPane.getGutter().setIconRowHeaderInheritsGutterBackground(true);
codeScrollPane.getGutter().setBackground(Color.BLACK);`

I feel like I must be doing something wrong, could you please point me in the right direction? Thanks!
