### ISSUE TITLE
How can I add a new language support,such as Matlab?

### ISSUE THREAD

**Issue by ZCY571864845** [bobbylight/RSyntaxTextArea#444]
**Describe the solution you'd like**

**Are there any workarounds?**
Are there any workarounds for folks while this feature is not yet implemented?

**Additional context**

**Comment by shinobisoft** [comment]
Check the Wiki. https://github.com/bobbylight/RSyntaxTextArea/wiki/Adding-Syntax-Highlighting-for-a-new-Language
