### ISSUE TITLE
Allow spaces to be used instead of tabs

### ISSUE THREAD

**Issue by OndrejSpanel** [bobbylight/RSyntaxTextArea#470]
**Describe the solution you'd like**

Autoindent currently uses Tab characters ("\t") for indentation. It could be nice to have this configurable, so that eg. "  " or "    " (two or four spaces) could be used instead, or any other whitespace character sequence.

**Are there any workarounds?**
I am not aware of any.

**Additional context**
Tabs are sometimes confusing when copying and pasting code from / to environment which does not use them.

**Comment by OndrejSpanel** [comment]
If this sounds like a reasonable suggestion, I think I can prepare a PR.

It seems it would be enough to adjust `insertNewlineWithAutoIndent` - automatic un-indentation in `CloseCurlyBraceAction` seems to be already flexible enough to handle any whitespace combinations very well.

**Comment by bobbylight** [comment]
This is already doable with `tabsEmulatedWithSpaces(true)`. Are you seeing a scenario where tabs are inserted if this property is set to `true`?

**Comment by OndrejSpanel** [comment]
I was not aware of that option. Sounds exactly like what I need, thanks.
