### ISSUE TITLE
codes were removed when split one line code to two lines

### ISSUE THREAD

**Issue by Yaqiang** [bobbylight/RSyntaxTextArea#484]
**Description**
Codes were removed when split one line code to two lines with Python syntax style. The bug occured when putting the mouse position in a code line and press 'Enter' button in keyboard.

**Steps to Reproduce**
I am using RSyntaxTextArea for Jython code editor in MeteoInfoLab (https://github.com/meteoinfo/MeteoInfo/blob/master/meteoinfo-lab/src/main/java/org/meteoinfo/lab/gui/EditorDockable.java#L171-L175).  MITextEditorPane is an extents of TextEditorPane with auto code completion (https://github.com/meteoinfo/MeteoInfo/blob/master/meteoinfo-console/src/main/java/org/meteoinfo/console/editor/MITextEditorPane.java).

**Screenshots**
![Before code line split](http://www.meteothink.org/downloads/temp/editor_bug_1.png)
![After code line split](http://www.meteothink.org/downloads/temp/editor_bug_2.png)

**Java version**
Java 11

**Comment by bobbylight** [comment]
Ouch, this is really bad, looks like a broken. I'll get a fix published ASAP, but I'd recommend pinning an older RSTA version that works until then!

**Comment by bobbylight** [comment]
This was broken in 3.3.1, please try pinning to 3.3.0 until I can get a 3.3.2 release out this weekend.

**Comment by Yaqiang** [comment]
Thanks for your information and I am waiting the 3.3.2 version.

**Comment by bobbylight** [comment]
Fixed in 3.3.2-SNAPSHOT on Sonatype. I'll publish 3.3.2 to Maven Central this weekend.
