### ISSUE TITLE
Add custom tokens for highlighting

### ISSUE THREAD

**Issue by MasterCoder21** [bobbylight/RSyntaxTextArea#486]
I'm making somewhat of an IDE for shaders (GLSL).  Though its syntax is a lot like C/C++, it doesn't highlight things like "uniform," "layout," or any other common GLSL keywords when I set the text area's highlighting language to C++.  If a method of adding additional tokens (words?) to highlight already exists, sorry in advance!  If not, I'd be very happy to see that implemented. 

Thank you!

**Comment by MasterCoder21** [comment]
Well, I just took a few seconds to actually read the README and I found the link to JFlex.  Though, I'm still wondering if adding custom highlighting be possible with JFlex?

**Comment by bobbylight** [comment]
These instructions walk you through creating a custom `TokenMaker`, either by parsing the text "manually" or via JFlex.

However, if what you want to render is really just a superset of C++, you can add additional keywords by extending `CPlusPlusTokenMaker` (or any of the built-in `TokenMaker`s) and extend this `addToken()` overload like so:

```java
@Override
public void addToken(Segment segment, int start, int end, int tokenType, int startOffset) {
   // This assumes all extra keywords are parsed as "identifiers."
   if (tokenType==TokenTypes.IDENTIFIER) {
      // "value" is e.g. TokenTypes.RESERVED_WORD, TokenTypes.FUNCTION, or however you want it styled
      int value = extraWordsToHighlight.get(segment, start, end);
      if (value != -1) {
         tokenType = value;
      }
   }
   super.addToken(segment, start, end, tokenType, startOffset);
}
```

Then install your custom TokenMaker via the "Plugging your TokenMaker into an application" instructions [here](https://github.com/bobbylight/RSyntaxTextArea/wiki/Adding-Syntax-Highlighting-for-a-new-Language#PluggingIntoApp).
