### ISSUE TITLE
Is it possible to make 2 methods public ?

### ISSUE THREAD

**Issue by nbauma109** [bobbylight/RSyntaxTextArea#493]
Is it possible to make 2 methods public ?
- [org.fife.ui.rtextarea.RTextArea.markAll(List<DocumentRange>)](https://github.com/java-decompiler/jd-gui/blob/b3c1ced04e571fc316648d114ff0c8121e051d8f/services/src/main/java/org/fife/ui/rtextarea/Marker.java#L23)
- [org.fife.ui.rtextarea.RTextArea.clearMarkAllHighlights()](https://github.com/java-decompiler/jd-gui/blob/b3c1ced04e571fc316648d114ff0c8121e051d8f/services/src/main/java/org/fife/ui/rtextarea/Marker.java#L27)

**Comment by bobbylight** [comment]
Fixed by the linked PR #493. Thanks again!
