### ISSUE TITLE
Python Fold Parser does not handle line continuation

### ISSUE THREAD

**Issue by awindillman** [bobbylight/RSyntaxTextArea#512]
Python uses the backslash '\' as a line continuation.  If there is a line continuation anywhere in the RSTA while code folds are being processed an exception is thrown.

**Steps to Reproduce**
Specific steps to reproduce the behavior:
1. Launch the demo App
2. Go into Python mode
3. Add a line continuation after an if (for example) and add anything to the next line
4. Exception thrown

This bug requires adding support for line continuation to the PythonFoldParser.  This is a small fix, and I will put in a pull request for it.

**Comment by bobbylight** [comment]
Thanks for the PR with the fix!
