### ISSUE TITLE
paintTabLines  Not effective

### ISSUE THREAD

**Issue by kemoving** [bobbylight/RSyntaxTextArea#516]
**Description**
The alignment lines do not take effect when the Margin is 0

**code**
org.fife.ui.rsyntaxtextarea.DefaultTokenPainter  Line 165

**quetion**
I don't understand why this('origX==host.getMargin().left') judgment is so

**Comment by bobbylight** [comment]
Can you provide a sample application showing this behavior? It seems to work for me after calling `setMargin(new Insets(0, 0, 0, 0))`:

![image](https://github.com/bobbylight/RSyntaxTextArea/assets/1631766/68f2efb3-090e-474f-99ad-690764b29d7d)

**Comment by bobbylight** [comment]
Closing as there has been no response in a few months. Please reopen if you can provide an [SSCCE](http://sscce.org/) that demonstrates the problem!
