### ISSUE TITLE
[feature] possibility to implement custom line number formatting

### ISSUE THREAD

**Issue by Mino260806** [bobbylight/RSyntaxTextArea#517]
## Feature Overview
This feature regards how line numbers are displayed in RTextScrollPane.
For example, instead of displaying 12, we would have the freedom to display any string like ١٢ (hindu-arabic) or 0xC (in hex)

### Why this feature is needed 
Some people who are used to other numeral systems would find it more convenient and natural to be read the line numbers in that system.

It's also a must when developing a Hex Editor using this library, because line numbers should be displayed as hex offsets

**Comment by bobbylight** [comment]
Fixed via #518. Thanks again for the PR!
