### ISSUE TITLE
rSyntaxTextArea cant be edited when reload by burpsuite

### ISSUE THREAD

**Issue by j7ur8** [bobbylight/RSyntaxTextArea#519]
**Description**
burpsuite is a security tool, support load swing-ui extension.
i have a tool used rSyntaxTextArea. when i first load it by burp, i can edit rSyntaxTextArea's textarea. 
But, if i reload it(unload it and load again), i can't edit rSyntaxTextArea's textarea.

**Java version**
no sense

**Comment by bobbylight** [comment]
I'd start with the burp suite folks, as I'm not familiar with that project, but I haven't heard of this issue elsewhere. If it turns out to be a bug in RSTA, feel free to open this ticket!
