### ISSUE TITLE
Make auto-indent character[s] configurable

### ISSUE THREAD

**Issue by awindillman** [bobbylight/RSyntaxTextArea#521]
Currently handleInsertBreakWithoutSelection() in RSyntaxTextAreaEditorKit will call replaceSelection with a hard coded "\t" when indention is needed.  The automatic indent character[s] should be configurable.  For example, a user commonly would prefer spaces vs a tab.  And space preferences will often vary by language or user.

There are no workarounds other than to turn off autoindent.

**Comment by bobbylight** [comment]
This is already handled by [RTextArea.setTabsEmulated(boolean)](https://github.com/bobbylight/RSyntaxTextArea/blob/2d7b80edd37b1eaf4e50b584b7ad59be7b22938b/RSyntaxTextArea/src/main/java/org/fife/ui/rtextarea/RTextAreaBase.java#L1143), which will cause all inserted tabs to be properly replaced with spaces aligned with tab stops.

**Comment by awindillman** [comment]
Thanks Bobby.  Sorry that I missed that.
