### ISSUE TITLE
Remove blank lines when loading an xml file

### ISSUE THREAD

**Issue by AmigaBlitter** [bobbylight/RSyntaxTextArea#531]
**Describe the solution you'd like**

When i open an Xml file RSyntaxTextArea adds blank lines

**Comment by bobbylight** [comment]
Hi @AmigaBlitter ! Can you provide a code snippet that demonstrates this behavior? I cannot reproduce it. Perhaps it is how you’re loading the text into the component.

**Comment by bobbylight** [comment]
Or are you saying you’d like to add blank lines? If so can you provide a before and after example of what you want to happen?

**Comment by bobbylight** [comment]
closing as no response in over 6 months. If you're still interested in this, please open a new ticket with more information about the bug or feature request.
