### ISSUE TITLE
How to enable foldable blocks?

### ISSUE THREAD

**Issue by TheEntropyShard** [bobbylight/RSyntaxTextArea#538]
So, my question is: How to enable foldable blocks, for, lets say, JSON? Is it possible? Like these:
![image](https://github.com/bobbylight/RSyntaxTextArea/assets/109285316/ad03dc2d-2c9a-46d6-a4db-65ed6b08e648)

**Comment by shinobisoft** [comment]
Check [here](https://javadoc.fifesoft.com/rsyntaxtextarea/org/fife/ui/rsyntaxtextarea/folding/FoldManager.html). You may also want to browse the wiki too.

**Comment by TheEntropyShard** [comment]
Thank you, I will look into that.
