### ISSUE TITLE
InsertQuoteAction overwrites trailing character after token instead of closing double quote in Python

### ISSUE THREAD

**Issue by paul-griffith** [bobbylight/RSyntaxTextArea#539]
**Description**
In (at least) Python syntax highlighting, the character _after_ the quote you just closed can be removed/overwritten.
![Kapture 2024-03-22 at 08 30 38](https://github.com/bobbylight/RSyntaxTextArea/assets/39345262/e6e7f67f-6282-49ea-ba7f-be3f197f2411)

`<speculation>`
This appears to be caused by the token maker. In the exact same scenario for Java, there will be a token `"something` with a type of `ERROR_STRING_DOUBLE`. But for Python, you get a token `"something` with a type of `LITERAL_STRING_DOUBLE_QUOTE`. This leads to a different branch in `InsertQuoteAction`, specifically this one:
```java
			if (tokenType == quoteType.validTokenType) {
				if (offs == t.getEndOffset() - 1) {
					textArea.moveCaretPosition(offs + 1); // Force a replacement to ensure undo is contiguous
					textArea.replaceSelection(stringifiedQuoteTypeCh);
					textArea.setCaretPosition(offs + 1);
				}
```
This seems to be the _cause_ of the issue, with the root being the token type spit out by the token maker.
`</speculation>`

**Steps to Reproduce**
1. Type a string such as `str("something)` into an RSyntaxTextArea with Python syntax highlighting.
2. Set the caret position between `g` and `)`.
3. Enter a double quote.

Here's a test case that reproduces in `RSyntaxTextAreaEditorKitInsertQuoteActionTest`:
```java
	@Test
	void testActionPerformedImpl_python_close_quote_overtypes() {
		String origContent = "call(\"function)";

		RSyntaxTextArea textArea = createTextArea(SyntaxConstants.SYNTAX_STYLE_PYTHON, origContent);
		textArea.setCaretPosition(origContent.indexOf("function") + 8);

		RecordableTextAction a = new RSyntaxTextAreaEditorKit.InsertQuoteAction("test",
			RSyntaxTextAreaEditorKit.InsertQuoteAction.QuoteType.DOUBLE_QUOTE);
		ActionEvent e = createActionEvent(textArea, "\"");
		a.actionPerformedImpl(e, textArea);

		Assertions.assertEquals("call(\"function\")", textArea.getText());
	}
```

**Expected behavior**
Double quotes should be closed 'correctly' without overtyping.

I'll also note, for the sake of it, that _single_ quotes work just fine.

**Comment by paul-griffith** [comment]
For a simple workaround (since my application will only ever be using Python in these editors), I'm simply overwriting the entry in the action map with base `InsertPairedCharacterAction` behavior:
```
put(
    RSyntaxTextAreaEditorKit.rstaDoubleQuoteAction,
    InsertPairedCharacterAction(RSyntaxTextAreaEditorKit.rstaDoubleQuoteAction, '"', '"')
)
```

**Comment by bobbylight** [comment]
Thanks for the bug report! This will be fixed in the next release.
