### ISSUE TITLE
Dot character (.) recognized as ERROR_IDENTIFIER in C#

### ISSUE THREAD

**Issue by SchiavoAnto** [bobbylight/RSyntaxTextArea#540]
**Description**
The dot character gets recognized as ERROR_IDENTIFIER and not as separator.

**Steps to Reproduce**
1. Clone this repo
2. Modify the demo application to include a C# example file, syntax option in the menubar and setting the style for the ERROR_IDENTIFIER token type (https://github.com/SchiavoAnto/RSyntaxTextArea-CSharp-Bug/commit/89647596f78aa03332bd3fd84210e22673691c66)
3. Run the application and select C# from the menubar
4. The dot in `Console.WriteLine` is red instead of black like other separators (for example a comma)

Alternatively, clone my fork demonstrating the issue, which is just this repo with the above mentioned changes applied.

**Expected behavior**
The dot should be recognized as a separator

**Actual behavior**
The dot is recognized as ERROR_IDENTIFIER

**Screenshots**
Before setting ERROR_IDENTIFIER to red (the dot uses the default ERROR_IDENTIFIER color):
![image](https://github.com/bobbylight/RSyntaxTextArea/assets/63348037/c231458d-73f5-40bc-b0e4-459a7ed036d9)
After setting ERROR_IDENTIFIER to red:
![image](https://github.com/bobbylight/RSyntaxTextArea/assets/63348037/4be51028-843a-47df-9394-37ceb1442bd1)

**Java version**
Demo application tested with Java 18 and 21. Actual project where I discovered the issue uses Java 21 and RSTA 3.4.0 from Maven.

**Comment by bobbylight** [comment]
Thanks for the bug report! It'll be fixed in the next release, which I hope to do soon

**Comment by SchiavoAnto** [comment]
Thank you!
