### ISSUE TITLE
Gutter does not auto-size to fit line numbers greater than 99 (with self-contained sample)

### ISSUE THREAD

**Issue by earlhood** [bobbylight/RSyntaxTextArea#541]
Sorry for the duplicate, but bug #511 is marked closed since it took a long time for me to get around to creating a self-contained example.  The final comment requested to reopen if needed, but there is no ability to reopen a bug item for non-committers.

Details of bug #511 still apply.  See attachment for a self-contained example that illustrates the problem. If you execute 'run.sh' it will compile the program and run it. You have to use the window manager to close/exit the window as I have neutered the buttons. The program is based on a dialog used in a product, so I had to remove references to other classes to keep the sample self-contained.

[rsyntaxarea-dialog-test.tar.gz](https://github.com/bobbylight/RSyntaxTextArea/files/14937617/rsyntaxarea-dialog-test.tar.gz)

**Comment by earlhood** [comment]
Problem still exists in v3.5.1.  Tested with Java 8 and Java 21.

**Comment by bobbylight** [comment]
Thanks for the bug report! I reproduced and fix this, it'll be in the 3.5.3 release.

**Comment by earlhood** [comment]
Verified the changes made fixed the problem within our application. Thank you very much!   Looking forward to the 3.5.3 release.
