### ISSUE TITLE
Clojure syntax highlighting: char literal double quote is treated as opening string

### ISSUE THREAD

**Issue by NoahTheDuke** [bobbylight/RSyntaxTextArea#543]
**Description**
Most character literals (which are mostly the same as in Java) are treated as chars, except for `"` (double-quote) which is always treated as an opening string.

**Steps to Reproduce**
I am new to RSyntaxTextArea but I'm using it in [clooj](https://github.com/clj-commons/clooj), which is where the screenshot below is from. I'm not exactly sure how to reproduce in another form.

**Expected behavior**
The `\"` is treated as a char instead of an opening string.

**Actual behavior**
It's treated as an opening string.

**Screenshots**
<img width="289" alt="image" src="https://github.com/bobbylight/RSyntaxTextArea/assets/603677/3e7e0d0b-e3ec-47fb-b5fd-d4a0d5b0bf1c">

**Java version**
```
$ lein --version
Leiningen 2.11.2 on Java 11.0.20 OpenJDK 64-Bit Server VM
```

**Additional context**
I tried to fix it, but the `flex` stuff was way over my head.

**Comment by bobbylight** [comment]
Thanks for the report!
