### ISSUE TITLE
Unnecessary Print

### ISSUE THREAD

**Issue by SamKry** [bobbylight/RSyntaxTextArea#561]
**Description**
Since v3.5.0 there is a System.out which is called on every search next request. Is this really necessary or a leftover from testing new code?

**Steps to Reproduce**
Specific steps to reproduce the behavior:
1. Open a find dialog and search for sth.

**Expected behavior**
No Print.

**Actual behavior**
Print

**Screenshots**
![image](https://github.com/user-attachments/assets/c121bdc1-edb2-49de-90da-eb8758651d1a)

Remove this line.

**Comment by SamKry** [comment]
I just saw that you already deleted the SysOut in the `SmartHighlightPainter`. Can you please release a new Version with the Fix? Thx

**Comment by remcopoelstra** [comment]
I think something may have gone wrong, I just updated to 3.5.1 and noticed the sysout messages, looking at the commit history I see it was indeed removed but also added back.

The ligatures support is looking very nice by the way!

**Comment by eybisi** [comment]
#https://github.com/bobbylight/RSyntaxTextArea/commit/bfc9cc93019eb1da0253ec054a8f863b2b1a71df adds back sysout messages. Is this intended ? @bobbylight

**Comment by hshafie** [comment]
May be not related but close.
Upgraded to 3.5.1 and when I select some text, I get:
... SmartHighlightPainter: rendering: 3662 - 3667
printed on the console, over and over, until I deselect the text.

**Comment by bobbylight** [comment]
argh, not sure how this happened! I'll fix this in a quick 3.5.2. Thanks folks

**Comment by bobbylight** [comment]
Fixed (for real this time, hopefully) via #566 which will be in 3.5.2.

**Comment by SamKry** [comment]
Hey
When do you plan to release the new version with the fix?
Would really appreciate it :)
