### ISSUE TITLE
Some debugging println() left when selecting some text

### ISSUE THREAD

**Issue by hshafie** [bobbylight/RSyntaxTextArea#566]
**Description**

Upgraded from 3.4.1 to 3.5.1 and when I select some text, I get:

```
... SmartHighlightPainter: rendering: 3662 - 3667
... SmartHighlightPainter: rendering: 3662 - 3667
... SmartHighlightPainter: rendering: 3662 - 3667
```

printed on the terminal, over and over, until I deselect the text.

**Steps to Reproduce**
1. Start any application using RSyntaxTextArea 3.5.1 from a terminal in order to see messages printed on it.
2. Select some text.
3. `... SmartHighlightPainter: rendering:...` is printed repeatedly on the terminal until I deselect the text.

**Expected behavior**
No messages should be printed on the terminal.

**Actual behavior**
Some messages are printed on the terminal.

**Java version**
openjdk version "22.0.2" 2024-07-16

**Additional context**
Regression. No such issue with 3.4.1

**Comment by bobbylight** [comment]
Thanks for the bug report!

**Comment by hshafie** [comment]
Thanks for the bug fix!
