### ISSUE TITLE
"Error waves" under text

### ISSUE THREAD

**Issue by olivbrau** [bobbylight/RSyntaxTextArea#569]
Hi,
Is there a standard way to show a kind of "error wave" under some portions of text in a RSyntaxTextArea ?
If no, do you know how I could easy implement this feature ?

For instance, my program analyse the code and can detect some errors that cannot be detected during the tokenisation of RSyntaxTextArea (cf. it is a longer analysis in a separate thread). And I would like to add a red error wave under the portions of text that are bad.

Here is an example to show what I'm trying to do :
I know that tokens can be underlined, but what I speak of is not in the same scope as token analysis.
for instance the code : string toto = 123 + "aze"
all 3 tokens are good and are to be shown in their correct token  style, but later, the 'analyser' detect that 123 cannot be added with a string and I would like to underline easly all the text  123 + "aze", leaving everything else in the same style

Thanks in advance !

Olivier

**Comment by Hasnatrasool163** [comment]
Hi Olivier,

There isn't a standard way built into RSyntaxTextArea to show an "error wave" under portions of text. However, you can easily implement this feature using a custom LayeredHighlighter in combination with the RSyntaxTextArea's built-in highlighter.

Here's a simple approach to achieve the error wave underline for the text portions that your program flags as errors. You can create a custom highlighter that paints a wavy underline below the text, and then apply it to the portions of text that are detected as errors by your analysis.
Step-by-Step Implementation:

    Create a Custom Highlighter: Use a custom LayeredHighlighter to paint a red wavy underline under the text.

    Highlight Errors Dynamically: After your program completes its analysis and identifies errors, use this highlighter to underline the erroneous text portions.

    Toggle Error States: You can also extend this to allow errors to be added and removed dynamically, which simulates a scenario where errors come and go as the analysis updates.

Here’s a complete working example of how you can implement this:
code:


import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rtextarea.RTextScrollPane;

import javax.swing.*;
import javax.swing.text.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 * This class demonstrates how to highlight errors with a red wavy underline in an RSyntaxTextArea.
 * It allows highlighting multiple portions of text and toggling the highlights dynamically.
 */
public class RSyntaxTextAreaErrorHighlighter extends JFrame {

    private RSyntaxTextArea textArea;
    private Highlighter highlighter;
    private List<Object> errorHighlights;

    /**
     * Constructor to initialize the error highlighter example for RSyntaxTextArea.
     */
    public RSyntaxTextAreaErrorHighlighter() {
        setTitle("RSyntaxTextArea - Multiple Error Highlights with Dynamic Update");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(600, 400);

        textArea = new RSyntaxTextArea(20, 60);
        textArea.setSyntaxEditingStyle(RSyntaxTextArea.SYNTAX_STYLE_JAVA);
        textArea.setCodeFoldingEnabled(true);

        String code = "string toto = 123 + \"aze\";\n" +
                      "int value = 456 + \"foo\";\n" +
                      "boolean flag = true + false;";
        textArea.setText(code);

        RTextScrollPane sp = new RTextScrollPane(textArea);
        getContentPane().add(sp);

        highlighter = textArea.getHighlighter();
        errorHighlights = new ArrayList<>();

        highlightErrors();

        JButton toggleButton = new JButton("Toggle Errors");
        toggleButton.addActionListener(e -> toggleErrorHighlight());
        getContentPane().add(toggleButton, BorderLayout.SOUTH);

        setVisible(true);
    }

    /**
     * Highlights all detected errors in the RSyntaxTextArea.
     */
    private void highlightErrors() {
        highlightError("123 + \"aze\"", Color.RED);
        highlightError("456 + \"foo\"", Color.RED);
        highlightError("true + false", Color.RED);
    }

    /**
     * Highlights a portion of the text as an error with a wavy underline.
     *
     * @param errorText The portion of text to highlight as an error.
     * @param color     The color of the underline for the error.
     */
    private void highlightError(String errorText, Color color) {
        String code = textArea.getText();
        int startOffset = code.indexOf(errorText);
        int endOffset = startOffset + errorText.length();

        Highlighter.HighlightPainter painter = new WaveUnderlineHighlightPainter(color);

        try {
            Object highlight = highlighter.addHighlight(startOffset, endOffset, painter);
            errorHighlights.add(highlight);
        } catch (BadLocationException e) {
            e.printStackTrace();
        }
    }

    /**
     * Clears all current error highlights.
     */
    private void clearErrorHighlights() {
        for (Object highlight : errorHighlights) {
            highlighter.removeHighlight(highlight);
        }
        errorHighlights.clear();
    }

    /**
     * Toggles error highlights on or off, simulating the fixing and reintroducing of errors.
     */
    private void toggleErrorHighlight() {
        if (errorHighlights.isEmpty()) {
            highlightErrors();
        } else {
            clearErrorHighlights();
        }
    }

    /**
     * Custom painter to draw wavy underlines for error highlights.
     */
    static class WaveUnderlineHighlightPainter extends LayeredHighlighter.LayerPainter {

        private final Color color;

        /**
         * Constructs a WaveUnderlineHighlightPainter with the specified color.
         *
         * @param color The color of the wavy underline.
         */
        public WaveUnderlineHighlightPainter(Color color) {
            this.color = color;
        }

        @Override
        public void paint(Graphics g, int offs0, int offs1, Shape bounds, JTextComponent c) {
            // Not used for layered highlights
        }

        @Override
        public Shape paintLayer(Graphics g, int offs0, int offs1, Shape bounds, JTextComponent c, View view) {
            try {
                Rectangle r0 = c.modelToView(offs0);
                Rectangle r1 = c.modelToView(offs1);

                Rectangle r = r0.union(r1);

                g.setColor(color);

                int waveHeight = 2;
                for (int x = r.x; x < r.x + r.width; x += 6) {
                    g.drawLine(x, r.y + r.height - waveHeight, x + 3, r.y + r.height);
                    g.drawLine(x + 3, r.y + r.height, x + 6, r.y + r.height - waveHeight);
                }

                return r;
            } catch (BadLocationException e) {
                e.printStackTrace();
            }
            return null;
        }
    }

    /**
     * Main method to run the example.
     *
     * @param args Command-line arguments.
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new RSyntaxTextAreaErrorHighlighter());
    }
}

How to Extend and Use It:

    Highlight Additional Errors: You can modify the highlightErrors() method to identify and underline different portions of text that your analyzer marks as incorrect. Simply add calls to highlightError() with the error string and desired color.

    Dynamic Error Toggling: The toggleErrorHighlight() method simulates fixing or reintroducing errors dynamically. You can adapt this logic based on how your error analysis runs, perhaps linking it to an external thread that triggers highlights as the analysis completes.

    Custom Painter: The custom WaveUnderlineHighlightPainter handles drawing a wavy underline. You can modify the appearance by tweaking how the waves are drawn if you'd prefer a different style or thickness.

This approach gives you the flexibility to highlight errors without interfering with the default token styles, allowing for analysis beyond tokenization.

![wavy_lines](https://github.com/user-attachments/assets/bc5ef331-4b30-41e1-963a-1ce910c2a244)

**Comment by Hasnatrasool163** [comment]
Use RSyntaxTextArea.addParser() to add your custom parser.
In your parser's parse() method, specify the positions where the errors should be highlighted.
You can apply a "wave underline" style using setUnderlineColor() and other styling options.

**Comment by olivbrau** [comment]
Thanks for your answer. I have just discovered this amazing feature (Parser).
I will have a look.
However, since the textarea is locked during parsing, the Parser must be fast : sometimes, my parser need some time for pathological bad expressions, to discover that it is indeed bad ... I will have to put a timer to avoid this and stop parsing if too long

**Comment by bobbylight** [comment]
You don't need to create your own `HighlightPainter` for this; that functionality is baked into the library.

Like you mentioned, you can create an implementation of the `Parser` interface (or `AbstractParser` base class) and add it to your `RSyntaxTextArea` instance. Any errors it identifies will automatically be rendered with squiggle underlines.

Documentation on the API is in the wiki here: [Example: Adding a parser for syntax checking](https://github.com/bobbylight/RSyntaxTextArea/wiki/Example:-Adding-a-parser-for-syntax-checking).

The simplest example is probably [PerlParser](https://github.com/bobbylight/RSTALanguageSupport/blob/master/RSTALanguageSupport/src/main/java/org/fife/rsta/ac/perl/PerlParser.java)in [RSTAUILanguageSupport](https://github.com/bobbylight/RSTALanguageSupport). That class actually launches the `perl` binary and parses the output to parse the file - not at all perfomant, but a simple example nonetheless. There are other examples in that library's source as well, of greater complexity.

See also [SpellingParser](https://github.com/bobbylight/SpellChecker/blob/master/SpellChecker/src/main/java/org/fife/ui/rsyntaxtextarea/spell/SpellingParser.java) in the [SpellChecker ](https://github.com/bobbylight/SpellChecker)library for another simple example - it squiggle-underlines spelling errors in the document using the 3rd-party Jazzy library.

**Comment by olivbrau** [comment]
Thanks, the perl example is great.
However, i wonder if taking the risk of waiting at max 10 sec is dangerous or not. I'm sure that the perl parser is fast and reliable, contrary to mine.
May be it would have been great if the parser had to parse in a separate thread, and parse() returned immediately.
Then a callback of the ParserManager shoud be called when parse is finished. When the callback is called or during parsing, if code as changed, parse() is called again, the parser could stop parsing if not finished yet and reparse etc.
In this way, the code editor is never blocked.
But may be is it harder to implement.
