### ISSUE TITLE
Bracket matching highlight gets stuck occasionally

### ISSUE THREAD

**Issue by oakes** [bobbylight/RSyntaxTextArea#72]
On occasion, I've noticed that the bracket matching highlight (when your cursor is at a bracket or paren and the matching one is highlighted) gets stuck and doesn't go away when the cursor is moved. I haven't been able to reproduce it reliably, unfortunately. I tend to edit with the Clojure syntax style turned on, but I imagine the bracket highlighting is a general feature. I'm using 2.5.3, and I don't recall it happening in 2.5.0.

**Comment by voodoo66** [comment]
I also noticed an issue with the bracket matching, it can be easily reproduced by typing two lines with an opening and closing bracket, e.g. "()\n()". If the caret position is at the end of the file, the bracket matching looks correct. But if you navigate the cursor to the first line (with the arrow up key), then it looks broken (see attached picture).
Using latest commit on the master branch: d84a498dd8c2e042ced9ccde4c96ea1d54770f68

![bracket_matching_issue](https://cloud.githubusercontent.com/assets/14852960/10119191/df48b3cc-648e-11e5-850a-936bbacaa08d.png)

**Comment by voodoo66** [comment]
I debug the code and found the place that draws the matching bracket rectangle. I just comment the relevant lines and it seems to work now.
Here are the lines which causes the problem, maybe it helps to fix it properly:
DefaultTokenPainter.java:144
```java
if (flushLen>0 && nextX>=clipStart) {
    if (bg!=null) {
        paintBackground(x,y, nextX-x,fm.getHeight(),
                        g, fm.getAscent(), host, bg);
    }
>   /*if (token.length()==1 && r!=null && r.x==x) {
>       ((RSyntaxTextAreaUI)host.getUI()).paintMatchedBracketImpl(g, host, r);
>   }*/
    g.setColor(fg);
    g.drawChars(text, flushIndex, flushLen, (int)x,(int)y);
}
```

**Comment by bobbylight** [comment]
I pushed a fix for the issue reported by @voodoo66 on 27sep2015.  I've verified that the `RSyntaxTextAreaEditorKit.IncreaseFontSizeAction` and `DecreaseFontSizeAction` update the matched-bracket highlight when used; @oakes, were you using a homebrew version of these actions when you did not see the fix perhaps?

As for other instances where the matched bracket painting breaks, please open a new ticket.

**Comment by Haeri** [comment]
I can still observe this issue with the newest git version (3.0.0-SNAPSHOT)

![Bracket Issue](http://monolith-code.net.tiberius.sui-inter.net/Upload/Bracket_Issue.gif)

I am simply using the setFont() method on the RSyntaxTextArea object.

![code](http://monolith-code.net.tiberius.sui-inter.net/Upload/code.png) 

I have also tried to throw in a repaint() at the end, but without success.
