### ISSUE TITLE
Double Click to Highlight occurrences

### ISSUE THREAD

**Issue by illumi** [bobbylight/RSyntaxTextArea#88]
Other editors have a feature where you can double click to select a word and it will highlight the other occurrences of this word in the editor. The behaviour is then to deselect the highlighted word occurrence(s) when clicked away from. An example of this feature can be demonstrated by the Notepad++ editor.

Perhaps it would also be nice to add integration with the RTextScrollPane to also mark position of occurrences on the scrollbar when highlighting or using the search feature.

**Comment by goranschwarz** [comment]
Below is a Quick Fix for this... 
I have **really** started to like this feature in Notepad++, and I get more and more dependent on it...  

Note: it doesn't work well in combination with normal searches etc... and it also reuses the same color...
So get a **proper** implementation of it would be **nice** ;)

The ClickListener() is just a wrapper for figuring out if it's a double/single click
```
// Poor-mans version of NotePad++ select a word and we highlight the word everywhere in the doc 
textArea.addMouseListener(new ClickListener()
{
	@Override
	public void doubleClick(MouseEvent e)
	{
		String str = textArea.getSelectedText();
		if (str != null)
		{
			SearchContext context = new SearchContext(str);
			context.setMarkAll(true);
			context.setMatchCase(true);
			context.setWholeWord(true);
			SearchEngine.markAll(textArea, context);
		}
	}
	@Override
	public void singleClick(MouseEvent e)
	{
		SearchContext context = new SearchContext();
		context.setMarkAll(true);
		context.setMatchCase(true);
		context.setWholeWord(true);
		SearchEngine.markAll(textArea, context);
	}
});

```

**Comment by Haeri** [comment]
Thats why I set the void org.fife.ui.rtextarea.RTextArea.clearMarkAllHighlights() to public in my fork :D
