### ISSUE TITLE
Block Selection

### ISSUE THREAD

**Issue by illumi** [bobbylight/RSyntaxTextArea#90]
I release there was some talk about Block Selection in the past, was there ever a conclusion about this with the move to newer Java versions?

**Comment by goranschwarz** [comment]
Any traction on the "Block Selection" feature?
(it has been open for a **while**)

**Comment by siggemannen** [comment]
I have implemented a very dirty version locally, and was not easy, but i'm not a great programmer swingwise either.
The way i did was to implement a mouse listener that creates multiple selection points on Alt-keydown to "fake" a column selection. Then you need to reimplement replaceSelection-method and similar with a version that honors replacement of multiple selections, and well as getSelection stuff for copy/paste operations, and there are a couple of such places. Another tricky part is column selections and tabs as well as "virtual space" stuff / jagged lines.

The part i'm not done with is to "keep" selection and caret marking after inserting a key. It's too bad java doesn't support this out of the box. Also, there is no/bad support for stuff like virtual space.

**Comment by bobbylight** [comment]
I thought this was in a branch (with bugs) but it isn't. I had done some work on it but like @siggemannen's attempt there were outstanding issues and it wasn't true multi-caret like folks expect these days. I'll see if I can fi d myocal branch with this work and push it as a starting point
